#!/usr/bin/env bash
# check-shields-up-paired-negative.test.sh — T15 self-application: the check-shields-up.sh gate
# MUST exit 0 when shields are correctly wired AND exit non-zero when they are not — so the gate
# is falsifiable (cannot always-pass) AND does not false-RED on the husky v9 hooksPath (#831).
#
# NON-VACUITY: check-shields-up SKIPs (exit 0) when its target dir is NOT a git repo. So this test
# `git init`s the scratch dir and sets core.hooksPath per-arm — otherwise every arm SKIPs and the
# test becomes a vacuous always-pass (the #832 trap). The POSITIVE arms (ii)/(iii) are the #832
# lesson: a paired-negative with only must-fail arms can't catch an always-fail gate.
#
# RESOLUTION, not string equality (2026-08-17): Check 1 resolves core.hooksPath (relative →
# against the git root, absolute → as-is) and asserts the resulting dir EXISTS. Arms (vi)–(viii)
# are that contract's controls. Note what arm (iii) used to prove: this fixture never created
# `.husky/_`, so the old literal compare passed a hooksPath pointing at a NONEXISTENT dir — the
# false-GREEN in miniature (gate green, every shield silently dead). The fixture now creates the
# wrapper dir, and (vii) asserts the missing-dir case reads RED.
#
# ARMS:
#   (i)    form-check: gate script exists and is executable
#   (ii)   POSITIVE: core.hooksPath=.husky (dir present)   → gate exits 0 (husky v8 convention)
#   (iii)  POSITIVE: core.hooksPath=.husky/_ (dir present) → gate exits 0 (husky v9 convention; #831 regression guard)
#   (iv)   NEGATIVE: core.hooksPath unset                  → gate exits non-zero
#   (v)    NEGATIVE: core.hooksPath=.git/hooks             → gate exits non-zero (relative, not a husky dir)
#   (vi)   POSITIVE: core.hooksPath=<abs>/.husky/_         → gate exits 0 (absolute form is valid; git honours it)
#   (vii)  NEGATIVE: core.hooksPath=.husky/_, dir ABSENT   → gate exits non-zero (git skips every shield SILENTLY)
#   (viii) NEGATIVE: core.hooksPath=<abs>/.git/hooks       → gate exits non-zero (absolute, but not a husky dir)
#   (ix)   control:  consumer pre-commit, no exemption      → gate exits non-zero
#   (x)    POSITIVE: consumer pre-commit exempted by name   → gate exits 0
#   (xi)   NEGATIVE: pre-commit exempted, pre-push dead     → gate exits non-zero
#   (xii)  NEGATIVE: pre-commit exempted, hooksPath unset   → gate exits non-zero
#
# SKIP condition: git not available (same graceful-degrade as the gate itself). rc=0 on SKIP, rc=1 on FAIL.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GATE_SCRIPT="$REPO_ROOT/packages/core/audit-self/check-shields-up.sh"

PASS=0; FAIL=0; SKIP=0
ok()   { PASS=$((PASS+1)); echo "✓ $1"; }
bad()  { FAIL=$((FAIL+1)); echo "✗ $1"; }
skip() { SKIP=$((SKIP+1)); echo "· $1"; }

# ─── Arm (i): form-check ──────────────────────────────────────────────────────
if [ -x "$GATE_SCRIPT" ]; then
  ok "(i) gate script $GATE_SCRIPT exists and is executable"
else
  bad "(i) gate script $GATE_SCRIPT missing or not executable"
fi

# ─── Skip-condition probe: is git resolvable? ────────────────────────────────
if ! command -v git &>/dev/null; then
  skip "(ii) git not available — arms (ii)–(v) SKIP (same condition as the gate)"
  skip "(iii) git not available — SKIP"
  skip "(iv) git not available — SKIP"
  skip "(v) git not available — SKIP"
  echo ""
  echo "PASS=$PASS FAIL=$FAIL SKIP=$SKIP"
  exit 0
fi

# ─── Scratch: isolated git repo with the two shield hooks ─────────────────────
SCRATCH=$(mktemp -d)
trap 'rm -rf "$SCRATCH"' EXIT

git -C "$SCRATCH" init -q
# Shield hooks the gate's Check 2 + Check 3 require (content + executable).
mkdir -p "$SCRATCH/.husky"
cat > "$SCRATCH/.husky/pre-commit" << 'EOF'
#!/usr/bin/env sh
# @aif-shield: pre-commit — framework-owned (GH #975)
npx lint-staged
EOF
cat > "$SCRATCH/.husky/pre-push" << 'EOF'
#!/usr/bin/env sh
npx tsx packages/core/hooks/pre-push.ts
EOF
chmod +x "$SCRATCH/.husky/pre-commit" "$SCRATCH/.husky/pre-push"
# husky v9's wrapper dir. Generated by `prepare` and gitignored in a real repo — created here so
# arms (iii)/(vi) exercise a hooksPath that RESOLVES to something, not just one that reads right.
mkdir -p "$SCRATCH/.husky/_"

# Run the gate against the scratch repo with a given hooksPath; echoes "<rc>".
run_gate() {  # $1 = hooksPath value, or empty string to unset
  if [ -z "$1" ]; then
    git -C "$SCRATCH" config --unset core.hooksPath 2>/dev/null || true
  else
    git -C "$SCRATCH" config core.hooksPath "$1"
  fi
  AIF_PROJECT_ROOT="$SCRATCH" bash "$GATE_SCRIPT" >/dev/null 2>&1
  echo $?
}

# ─── Arm (ii): POSITIVE — core.hooksPath=.husky → gate exits 0 ───────────────
RC=$(run_gate ".husky")
if [ "$RC" -eq 0 ]; then
  ok "(ii) POSITIVE: core.hooksPath=.husky → gate exits 0 (rc=$RC) — v8 wiring accepted"
else
  bad "(ii) POSITIVE: core.hooksPath=.husky → gate exited non-zero (rc=$RC) — gate rejects a valid wiring (always-fail?)"
fi

# ─── Arm (iii): POSITIVE (#831 regression guard) — .husky/_ → gate exits 0 ───
RC=$(run_gate ".husky/_")
if [ "$RC" -eq 0 ]; then
  ok "(iii) POSITIVE: core.hooksPath=.husky/_ → gate exits 0 (rc=$RC) — husky v9 wiring accepted (#831)"
else
  bad "(iii) POSITIVE: core.hooksPath=.husky/_ → gate exited non-zero (rc=$RC) — #831 false-RED on husky v9"
fi

# ─── Arm (iv): NEGATIVE — core.hooksPath unset → gate exits non-zero ─────────
RC=$(run_gate "")
if [ "$RC" -ne 0 ]; then
  ok "(iv) NEGATIVE: core.hooksPath unset → gate exits non-zero (rc=$RC) — unwired shields caught"
else
  bad "(iv) NEGATIVE: core.hooksPath unset → gate exited 0 — gate accepts unwired shields (vacuous pass)"
fi

# ─── Arm (v): NEGATIVE — core.hooksPath=.git/hooks (wrong) → gate exits non-zero ─
RC=$(run_gate ".git/hooks")
if [ "$RC" -ne 0 ]; then
  ok "(v) NEGATIVE: core.hooksPath=.git/hooks → gate exits non-zero (rc=$RC) — wrong hooksPath caught"
else
  bad "(v) NEGATIVE: core.hooksPath=.git/hooks → gate exited 0 — gate accepts a wrong hooksPath (vacuous pass)"
fi

# ─── Arm (vi): POSITIVE — ABSOLUTE hooksPath → gate exits 0 ──────────────────
# git honours an absolute core.hooksPath as-is, and on a multi-worktree clone it is the form
# that keeps shields armed in checkouts where husky never ran. The pre-2026-08-17 literal
# compare called this "shields not pointing to the installed hooks" — a permanent false-RED.
RC=$(run_gate "$SCRATCH/.husky/_")
if [ "$RC" -eq 0 ]; then
  ok "(vi) POSITIVE: core.hooksPath=<abs>/.husky/_ → gate exits 0 (rc=$RC) — absolute wiring accepted"
else
  bad "(vi) POSITIVE: core.hooksPath=<abs>/.husky/_ → gate exited non-zero (rc=$RC) — false-RED on an absolute hooksPath that git honours"
fi

# ─── Arm (vii): NEGATIVE — hooksPath names a husky dir that does NOT exist ───
# The false-GREEN the literal compare had: git finds no hook at a nonexistent path and skips
# every shield SILENTLY, so this must read RED. Restore the dir afterwards for later arms.
rm -rf "$SCRATCH/.husky/_"
RC=$(run_gate ".husky/_")
mkdir -p "$SCRATCH/.husky/_"
if [ "$RC" -ne 0 ]; then
  ok "(vii) NEGATIVE: core.hooksPath=.husky/_ with the dir absent → gate exits non-zero (rc=$RC) — silently-dead shields caught"
else
  bad "(vii) NEGATIVE: core.hooksPath=.husky/_ with the dir absent → gate exited 0 — gate accepts a hooksPath git cannot resolve (false-GREEN, every shield dead)"
fi

# ─── Arm (viii): NEGATIVE — ABSOLUTE but not a husky dir → gate exits non-zero ─
# Resolution must not become blanket acceptance: an absolute path is still name-checked.
RC=$(run_gate "$SCRATCH/.git/hooks")
if [ "$RC" -ne 0 ]; then
  ok "(viii) NEGATIVE: core.hooksPath=<abs>/.git/hooks → gate exits non-zero (rc=$RC) — non-husky absolute path caught"
else
  bad "(viii) NEGATIVE: core.hooksPath=<abs>/.git/hooks → gate exited 0 — resolution degraded into accepting any absolute path"
fi

# ─── Arms (ix)–(xii): a consumer-owned hook is skipped, the rest is still checked ─
# install.sh keeps a consumer's own .husky/<hook> (HUSKY_CONSUMER_HOOKS) and passes the names in
# AIF_SHIELDS_CONSUMER_HOOKS. Only those hooks are exempt: hooksPath and the other hook must still be
# checked, or one kept pre-commit would hide a dead push shield (critical-review wave 2, cold-review F6).
cp "$SCRATCH/.husky/pre-commit" "$SCRATCH/pre-commit.framework"
printf '#!/usr/bin/env sh\necho consumer-own-pre-commit\n' > "$SCRATCH/.husky/pre-commit"
run_gate_consumer() {  # $1 = hooksPath value or empty; AIF_SHIELDS_CONSUMER_HOOKS=pre-commit
  if [ -z "$1" ]; then
    git -C "$SCRATCH" config --unset core.hooksPath 2>/dev/null || true
  else
    git -C "$SCRATCH" config core.hooksPath "$1"
  fi
  GATE_OUT=$(AIF_SHIELDS_CONSUMER_HOOKS="pre-commit" AIF_PROJECT_ROOT="$SCRATCH" bash "$GATE_SCRIPT" 2>&1)
  echo $? > "$SCRATCH/.rc"
}
RC=$(run_gate ".husky")
if [ "$RC" -ne 0 ]; then
  ok "(ix) control: a consumer pre-commit without the exemption → gate exits non-zero (rc=$RC)"
else
  bad "(ix) control: a consumer pre-commit without the exemption → gate exited 0 — (x) would prove nothing"
fi
run_gate_consumer ".husky"; RC=$(cat "$SCRATCH/.rc")
if [ "$RC" -eq 0 ] && printf '%s\n' "$GATE_OUT" | grep -q 'pre-commit: your own hook'; then
  ok "(x) POSITIVE: AIF_SHIELDS_CONSUMER_HOOKS=pre-commit → the kept hook is skipped by name, gate exits 0"
else
  bad "(x) POSITIVE: AIF_SHIELDS_CONSUMER_HOOKS=pre-commit → rc=$RC or no «your own hook» line"
fi
chmod -x "$SCRATCH/.husky/pre-push"
run_gate_consumer ".husky"; RC=$(cat "$SCRATCH/.rc")
chmod +x "$SCRATCH/.husky/pre-push"
if [ "$RC" -ne 0 ]; then
  ok "(xi) NEGATIVE: pre-commit exempt, pre-push not executable → gate exits non-zero (rc=$RC) — the push shield is still checked"
else
  bad "(xi) NEGATIVE: pre-commit exempt, pre-push not executable → gate exited 0 — the exemption hid a dead push shield"
fi
run_gate_consumer ""; RC=$(cat "$SCRATCH/.rc")
if [ "$RC" -ne 0 ]; then
  ok "(xii) NEGATIVE: pre-commit exempt, core.hooksPath unset → gate exits non-zero (rc=$RC) — hooksPath is still checked"
else
  bad "(xii) NEGATIVE: pre-commit exempt, core.hooksPath unset → gate exited 0 — the exemption hid unwired hooks"
fi
cp "$SCRATCH/pre-commit.framework" "$SCRATCH/.husky/pre-commit"

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "PASS=$PASS FAIL=$FAIL SKIP=$SKIP"
[ "$FAIL" -eq 0 ]
