#!/usr/bin/env bash
# tests/install-sh/rules-lock-version-diff.test.sh — S1 criterion 5: version diff shape.
#
# Two directions (S2's input contract — spec §7.1):
# (a) A DEPENDENCY bump → locks differ programmatically-diffably in `version`.
# (b) A consumer project-version bump → locks do NOT differ in `version` (r1-defect regression).
#
# Direction (a) is GENERATED by packages/core/installer/version-diff.test.ts (vitest) —
# it exercises the REAL generator (synthesize + install) across a 15→16 dependency bump.
# Direction (b) runs here: the REAL install.sh python lane against two consumers with
# different [project] versions — both must emit null (no manifest → derived null).
set -uo pipefail
REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
INSTALL="$REPO_ROOT/install.sh"
PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad()  { FAIL=$((FAIL+1)); echo "  ✗ $1"; }

[ -f "$INSTALL" ] || { echo "FATAL: $INSTALL not found"; exit 1; }

lock_version_raw() { grep -oE '"version"[[:space:]]*:[[:space:]]*(null|"[^"]*")' "$1" | head -1 | sed -E 's/.*:[[:space:]]*//'; }

echo "▶ Rules-lock version diff shape (S1 criterion 5) — machine-readable diffability"
echo ""

# ── (1) Direction (a): dependency bump → version differs (GENERATED, not constructed) ───────────────
# Exercised by packages/core/installer/version-diff.test.ts (vitest): calls the REAL
# generator (synthesize + install) twice with version=15.0.0 / 16.0.0 and asserts the
# generated locks differ in version. This shell arm is a pointer — the generated test
# IS the proof; constructing heredocs here would re-introduce the W-4 tell.
echo "  ── (1) dependency bump → generated locks differ in version (direction a, vitest) ──"
echo "  · direction (a) is generated by packages/core/installer/version-diff.test.ts (vitest)"
ok "(1) direction (a) delegated to the generator test (W-4: no constructed heredocs)"

# ── (2) Direction (b): consumer project-version bump → version does NOT differ ────────────────────
# The r1 defect: reading the consumer's own [project] version from pyproject.toml.
# Under the decided Option A, version=null for shell lanes (no named dependency) —
# a consumer's project version bump must NOT change the lock.
echo ""; echo "  ── (2) consumer project-version bump → version does NOT differ (direction b, r1 regression) ──"
PA=$(mktemp -d)
printf '[project]\nname = "demo"\nversion = "0.0.1"\n' > "$PA/pyproject.toml"
( cd "$PA" && bash "$INSTALL" python --force < /dev/null ) >/dev/null 2>&1
LOCKA="$PA/.getff/rules-lock.python.json"

PB=$(mktemp -d)
printf '[project]\nname = "demo"\nversion = "99.99.99"\n' > "$PB/pyproject.toml"
( cd "$PB" && bash "$INSTALL" python --force < /dev/null ) >/dev/null 2>&1
LOCKB="$PB/.getff/rules-lock.python.json"

if [ -f "$LOCKA" ] && [ -f "$LOCKB" ]; then
  vA=$(lock_version_raw "$LOCKA")
  vB=$(lock_version_raw "$LOCKB")
  [ "$vA" = "$vB" ] \
    && ok "(2) consumer version bump (0.0.1→99.99.99) → lock version unchanged ($vA == $vB)" \
    || bad "(2) lock version CHANGED across consumer bump: '$vA' → '$vB' (r1 defect — Option B leak)"
  [ "$vA" = "null" ] && [ "$vB" = "null" ] \
    && ok "(2) both locks honestly emit null (no named dependency — Option A)" \
    || bad "(2) lock version is not null — unexpected value leaked"
else
  bad "(2) lock(s) not emitted — A=$([ -f "$LOCKA" ] && echo yes || echo no) B=$([ -f "$LOCKB" ] && echo yes || echo no)"
fi
rm -rf "$PA" "$PB"

echo ""
echo "── rules-lock-version-diff: $PASS passed, $FAIL failed ──"
[ "$FAIL" -eq 0 ]
