#!/usr/bin/env bash
# skill-context-evolve-coownership — a shipped skill-context override is CO-OWNED with /aif-evolve.
#
# WHY: getff ships three overrides into `.ai-factory/skill-context/<skill>/SKILL.md`, and that
# directory is AI Factory's own evolution store. AIF 2.11.0 `skills/aif-evolve/SKILL.md:40-45`
# names `.ai-factory/skill-context/<skill-name>/SKILL.md` «the ONLY correct target for built-in
# skill improvements», and its §Artifact Ownership claims `.ai-factory/skill-context/*` outright.
# AIF offers no fenced section, sibling file or include it would preserve — its skills read the
# one SKILL.md per skill and nothing else — so co-ownership has to live on getff's side.
# Whole-file delivery collided with that store both ways (measured 2026-09-28 on a throwaway
# consumer before this fix):
#   1. install (copy_safe, skip-if-exists): an evolved file made getff print «exists — skipping»
#      and getff's review conventions never arrived — silently.
#   2. --refresh (refresh_safe, overwrite): every rule /aif-evolve had accumulated left the live
#      file (a copy went to .ai-factory/refresh-conflicts/, which no AIF skill reads).
# install_skill_context (setup.d/lib.sh) routes both paths through merge_fenced: getff owns only
# its `getff:begin section=getff-skill-context` block; everything outside it is evolve's.
#
# SHAPE (mirrors fence-agents-coownership.test.sh):
#   §0 REVISION REGISTER — every revision of every template in git history (and the working tree)
#      has its row in SKILL_CONTEXT_SHIPPED_REVISIONS, the list legacy copies are recognised by.
#   §1 CASE MATRIX (unit) — sources setup.d/lib.sh and drives install_skill_context directly,
#      including the legacy-migration branches a single install path cannot reach.
#   §2 PAIRED NEGATIVE — the SAME predicates run against the old whole-file verbs (copy_safe /
#      refresh_safe) and must report both failure modes, or they were vacuous.
#   §3 WIRING (integration) — REAL install.sh runs on the npm and python lanes, install then
#      --refresh, proving every delivery site calls the helper.
# shellcheck disable=SC2034,SC2015,SC2016  # SC2034: PKG_ROOT/FORCE/DRY_RUN/SKIPPED/PROJECT_ROOT are read by
# the sourced setup.d/lib.sh, not here; SC2015: `pred && ok || bad` is safe — ok/bad never fail;
# SC2016: backticks in single quotes are Markdown code spans in fixture text, not expansions.
set -uo pipefail
REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad() { FAIL=$((FAIL+1)); echo "  ✗ $1"; }

SRC_REL="packages/core/templates/shared/skill-context/aif-review/SKILL.md"
SRC="$REPO_ROOT/$SRC_REL"
SC_REL=".ai-factory/skill-context/aif-review/SKILL.md"
BEG='<!-- getff:begin section=getff-skill-context'
END='<!-- getff:end section=getff-skill-context -->'
# A heading that occurs exactly once in the template: counting it proves getff's content is present
# AND not duplicated (a legacy copy left beside a new fenced one would count 2).
GETFF_LINE='## MUST additionally check — test quality'

count() { grep -cF -- "$1" "$2" 2>/dev/null || true; }
# Whole marker LINES only: a rule that quotes the marker inline is prose, not a fence (case 6).
fence_ok() {
  [ "$(grep -cE '^<!-- getff:begin section=getff-skill-context( [^>]*)? -->$' "$1" 2>/dev/null)" = "1" ] \
    && [ "$(grep -cxF -- "$END" "$1" 2>/dev/null)" = "1" ]
}
getff_once() { [ "$(count "$GETFF_LINE" "$1")" = "1" ]; }

# What /aif-evolve step 7.2 writes: its own header template when the file is new …
evolve_create() {
  mkdir -p "$(dirname "$1")"
  cat > "$1" <<'EOF'
# Project Rules for /aif-review

> Auto-generated by `/aif-evolve`. Do not edit manually.
> Last updated: 2026-09-20 10:00
> Based on: 3 analyzed patches

## Rules

### Null-check optional DB relations
**Source**: 2026-09-18-null-relation.md
**Rule**: EVOLVED-RULE-KEEPME flag every access to an optional relation without a null check.
EOF
}
# … and «read it first, then add a new rule» when the file already exists.
evolve_add() {  # $1 = file, $2 = rule marker
  printf '\n### Rule %s\n**Source**: 2026-09-21-patch.md\n**Rule**: %s keep this project rule.\n' "$2" "$2" >> "$1"
}

hash256() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

# lib.sh expects these from the install.sh dispatcher scope.
PKG_ROOT="$REPO_ROOT"
FORCE=""
DRY_RUN=""
SKIPPED=()
# shellcheck source=/dev/null
source "$REPO_ROOT/setup.d/lib.sh"
command -v install_skill_context >/dev/null 2>&1 \
  || bad "install_skill_context is not defined in setup.d/lib.sh (no co-owned delivery verb)"

# consumer — a fresh consumer root (callers set PROJECT_ROOT for the manifest lookup).
consumer() { mktemp -d; }

SKILLS="aif-review aif-rules-check aif-orchestrator-discipline"
tpl() { echo "packages/core/templates/shared/skill-context/$1/SKILL.md"; }
# history_blobs <repo-relative path> — every distinct blob that path ever had on this branch.
history_blobs() {
  local c
  for c in $(git -C "$REPO_ROOT" rev-list HEAD -- "$1"); do
    git -C "$REPO_ROOT" rev-parse -q --verify "$c:$1" || true
  done | sort -u
}

echo "── §0 shipped-revision register (SKILL_CONTEXT_SHIPPED_REVISIONS) ──"
TMPREV=$(mktemp)
for sk in $SKILLS; do
  p=$(tpl "$sk"); n_rev=0; n_missing=0
  for blob in $(history_blobs "$p") WORKTREE; do
    if [ "$blob" = WORKTREE ]; then cp "$REPO_ROOT/$p" "$TMPREV"; else git -C "$REPO_ROOT" cat-file -p "$blob" > "$TMPREV"; fi
    n_rev=$((n_rev+1))
    row=$(_skill_context_revision_row "$sk" "$TMPREV" 2>/dev/null)
    if [ -z "$row" ] || ! grep -qxF -- "$row" <<<"${SKILL_CONTEXT_SHIPPED_REVISIONS:-}"; then
      n_missing=$((n_missing+1))
      echo "    missing row for $p ($blob) — add to SKILL_CONTEXT_SHIPPED_REVISIONS in setup.d/lib.sh:"
      echo "    $row"
    fi
  done
  [ "$n_missing" = 0 ] \
    && ok "§0 $sk: all $n_rev revisions (git history + working tree) are registered" \
    || bad "§0 $sk: $n_missing of $n_rev revisions missing from the register (a legacy copy of those is never recognised)"
done

echo "── §1 case matrix (install_skill_context direct) ──"

# (0) fresh destination → the file is our fenced block, template body without its frontmatter
W=$(consumer); PROJECT_ROOT="$W"
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
if [ -f "$W/$SC_REL" ] && fence_ok "$W/$SC_REL" && getff_once "$W/$SC_REL"; then
  ok "(0) fresh: one fenced block carrying the template body"
else
  bad "(0) fresh: expected 1 begin / 1 end / 1 template heading, got $(count "$BEG" "$W/$SC_REL")/$(count "$END" "$W/$SC_REL")/$(count "$GETFF_LINE" "$W/$SC_REL")"
fi
[ "$(count 'name: aif-review-project-context' "$W/$SC_REL")" = "0" ] \
  && ok "(0) fresh: template YAML frontmatter is not copied into the co-owned file" \
  || bad "(0) fresh: frontmatter landed mid-file inside the fence"

# (1) FAILURE MODE 1 — /aif-evolve wrote the file first → getff content lands, evolved rules stay
W=$(consumer); PROJECT_ROOT="$W"
evolve_create "$W/$SC_REL"
PRE=$(cat "$W/$SC_REL")
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
if getff_once "$W/$SC_REL" && fence_ok "$W/$SC_REL"; then
  ok "(1) evolved file present at install: getff's content landed as one fenced block"
else
  bad "(1) evolved file present at install: getff's content did NOT land (failure mode 1)"
fi
case "$(cat "$W/$SC_REL")" in
  "$PRE"*) ok "(1) evolved file present at install: every evolved byte kept, in place (block appended after)" ;;
  *)       bad "(1) evolved file present at install: evolve's content was altered or moved" ;;
esac

# (1b) second run → byte-identical (no duplicated block, no churn)
SNAP1=$(cat "$W/$SC_REL")
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
[ "$SNAP1" = "$(cat "$W/$SC_REL")" ] \
  && ok "(1b) idempotence: a second run leaves the file byte-identical" \
  || bad "(1b) idempotence: a second run changed the file"

# (2) FAILURE MODE 2 — evolve adds a rule after install → the refresh keeps it
evolve_add "$W/$SC_REL" EVOLVED-SECOND-KEEPME
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
if grep -qF EVOLVED-RULE-KEEPME "$W/$SC_REL" && grep -qF EVOLVED-SECOND-KEEPME "$W/$SC_REL" \
   && getff_once "$W/$SC_REL" && fence_ok "$W/$SC_REL"; then
  ok "(2) rules evolve added after install survive the re-delivery (failure mode 2)"
else
  bad "(2) re-delivery lost an evolved rule or duplicated getff's block (failure mode 2)"
fi

# (2b) a NEW template version replaces only getff's block; evolved rules untouched
NEWSRC=$(mktemp)
sed "s/^$GETFF_LINE\$/## MUST additionally check — NEW-GETFF-VERSION/" "$SRC" > "$NEWSRC"
install_skill_context "$NEWSRC" "$W/$SC_REL" >/dev/null 2>&1
if [ "$(count 'NEW-GETFF-VERSION' "$W/$SC_REL")" = "1" ] && [ "$(count "$GETFF_LINE" "$W/$SC_REL")" = "0" ] \
   && grep -qF EVOLVED-RULE-KEEPME "$W/$SC_REL" && grep -qF EVOLVED-SECOND-KEEPME "$W/$SC_REL"; then
  ok "(2b) template update: getff's block now carries the new version, evolved rules untouched"
else
  bad "(2b) template update: old getff text survived, new text missing, or an evolved rule was lost"
fi

# (3) LEGACY — a pre-fix whole-file copy, untouched → adopted, no duplicate template
W=$(consumer); PROJECT_ROOT="$W"
mkdir -p "$(dirname "$W/$SC_REL")"; cp "$SRC" "$W/$SC_REL"
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
if fence_ok "$W/$SC_REL" && getff_once "$W/$SC_REL"; then
  ok "(3) legacy pristine copy: adopted into one fenced block (template not duplicated)"
else
  bad "(3) legacy pristine copy: $(count "$GETFF_LINE" "$W/$SC_REL") template copies / fence $(count "$BEG" "$W/$SC_REL")"
fi

# (3b) LEGACY — the current template + rules evolve appended → split: ours fenced, theirs kept
W=$(consumer); PROJECT_ROOT="$W"
mkdir -p "$(dirname "$W/$SC_REL")"; cp "$SRC" "$W/$SC_REL"
evolve_add "$W/$SC_REL" EVOLVED-LEGACY-KEEPME
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
if fence_ok "$W/$SC_REL" && getff_once "$W/$SC_REL" && grep -qF EVOLVED-LEGACY-KEEPME "$W/$SC_REL"; then
  ok "(3b) legacy copy + appended evolve rules: split — template fenced once, evolved rule kept"
else
  bad "(3b) legacy copy + appended evolve rules: template $(count "$GETFF_LINE" "$W/$SC_REL")x, evolved $(count EVOLVED-LEGACY-KEEPME "$W/$SC_REL")x"
fi

# (3c) LEGACY — every OLDER revision getff shipped (git history), fence-less, NO refresh baseline,
#      with a rule evolve appended → recognised by the register: the old getff text is replaced by
#      the current block, the evolved rule kept. Without the register a copy that predated the
#      baseline manifest kept its stale text beside the new block forever (H1 twice).
OLD=$(mktemp)
sed "s/^$GETFF_LINE\$/## MUST additionally check — OLD-GETFF-VERSION/" "$SRC" > "$OLD"
for sk in $SKILLS; do
  p=$(tpl "$sk"); cur=$(git -C "$REPO_ROOT" hash-object "$REPO_ROOT/$p"); h1=$(grep -m1 '^# ' "$REPO_ROOT/$p")
  for blob in $(history_blobs "$p"); do
    [ "$blob" = "$cur" ] && continue
    W=$(consumer); PROJECT_ROOT="$W"; d="$W/.ai-factory/skill-context/$sk/SKILL.md"
    mkdir -p "$(dirname "$d")"; git -C "$REPO_ROOT" cat-file -p "$blob" > "$d"
    oldonly=$(grep -vxF -f "$REPO_ROOT/$p" "$d" | grep -v '^[[:space:]]*$' | head -n 1)
    evolve_add "$d" EVOLVED-OLDREV-KEEPME
    install_skill_context "$REPO_ROOT/$p" "$d" >/dev/null 2>&1
    if fence_ok "$d" && [ "$(grep -cxF -- "$h1" "$d")" = "1" ] && grep -qF EVOLVED-OLDREV-KEEPME "$d" \
       && { [ -z "$oldonly" ] || [ "$(grep -cxF -- "$oldonly" "$d")" = "0" ]; }; then
      ok "(3c) legacy $sk revision ${blob:0:8}, no baseline: old text replaced, evolved rule kept"
    else
      bad "(3c) legacy $sk revision ${blob:0:8}: H1 $(grep -cxF -- "$h1" "$d")x, stale line $(grep -cxF -- "$oldonly" "$d")x, evolved $(count EVOLVED-OLDREV-KEEPME "$d")x"
    fi
  done
done

# (3e) LEGACY, CRLF — a delivered copy an editor rewrote with CRLF line ends is still that copy
W=$(consumer); PROJECT_ROOT="$W"
mkdir -p "$(dirname "$W/$SC_REL")"; cp "$SRC" "$W/$SC_REL"; evolve_add "$W/$SC_REL" EVOLVED-CRLF-KEEPME
sed 's/$/\r/' "$W/$SC_REL" > "$W/x" && mv "$W/x" "$W/$SC_REL"
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
if fence_ok "$W/$SC_REL" && getff_once "$W/$SC_REL" && grep -qF EVOLVED-CRLF-KEEPME "$W/$SC_REL"; then
  ok "(3e) legacy CRLF copy + evolve rule: split like an LF copy (template once, evolved kept)"
else
  bad "(3e) legacy CRLF copy: template $(count "$GETFF_LINE" "$W/$SC_REL")x, evolved $(count EVOLVED-CRLF-KEEPME "$W/$SC_REL")x"
fi

# (3d) LEGACY — unprovable (older version NOT on record, evolve edited mid-file) → nothing removed
W=$(consumer); PROJECT_ROOT="$W"
mkdir -p "$(dirname "$W/$SC_REL")"
{ head -n 6 "$OLD"; echo '> Last updated: 2026-09-21 EVOLVED-MIDFILE-KEEPME'; tail -n +7 "$OLD"; } > "$W/$SC_REL"
PRE=$(cat "$W/$SC_REL")
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
case "$(cat "$W/$SC_REL")" in
  "$PRE"*) if fence_ok "$W/$SC_REL" && getff_once "$W/$SC_REL"; then
             ok "(3d) legacy, unprovable split: every existing byte kept, current template appended fenced"
           else
             bad "(3d) legacy, unprovable split: existing bytes kept but the fenced block is wrong"
           fi ;;
  *) bad "(3d) legacy, unprovable split: bytes getff cannot attribute were removed or rewritten" ;;
esac
# (3d') the same unprovable copy in CRLF still gets the «older getff copy» notice (H1 matched sans \r)
W=$(consumer); PROJECT_ROOT="$W"
mkdir -p "$(dirname "$W/$SC_REL")"; sed 's/$/\r/' "$OLD" > "$W/$SC_REL"
OUT=$(install_skill_context "$SRC" "$W/$SC_REL" 2>&1)
case "$OUT" in
  *"older getff copy"*) ok "(3d') unprovable CRLF copy: the kept-older-copy notice is still printed" ;;
  *) bad "(3d') unprovable CRLF copy: no notice — the consumer is not told getff text was left beside the block" ;;
esac

# (4) Layer 3 — a sibling SKILL.override.md means consumer-owned: nothing written
W=$(consumer); PROJECT_ROOT="$W"
evolve_create "$W/$SC_REL"
touch "$W/.ai-factory/skill-context/aif-review/SKILL.override.md"
PRE=$(cat "$W/$SC_REL")
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
[ "$PRE" = "$(cat "$W/$SC_REL")" ] \
  && ok "(4) .override.md present: file left untouched (Layer 3)" \
  || bad "(4) .override.md present: file was written anyway"

# (5) --dry-run writes nothing, on the fresh path and on the legacy-split path
W=$(consumer); PROJECT_ROOT="$W"
DRY_RUN="--dry-run"
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
[ ! -e "$W/$SC_REL" ] && ok "(5) dry-run fresh: no file created" || bad "(5) dry-run fresh: a file was created"
mkdir -p "$(dirname "$W/$SC_REL")"; cp "$SRC" "$W/$SC_REL"; evolve_add "$W/$SC_REL" EVOLVED-DRY
PRE=$(cat "$W/$SC_REL")
install_skill_context "$SRC" "$W/$SC_REL" >/dev/null 2>&1
[ "$PRE" = "$(cat "$W/$SC_REL")" ] && ok "(5) dry-run legacy split: file untouched" || bad "(5) dry-run legacy split: file was rewritten"
DRY_RUN=""

# (6) a rule that QUOTES the begin marker inline is prose, not a fence (whole-line match only)
QUOTE='**Rule**: never edit text between `<!-- getff:begin section=getff-skill-context … -->` and its end marker.'
W=$(consumer); PROJECT_ROOT="$W"; d="$W/$SC_REL"
evolve_create "$d"; printf '\n### Leave the getff block alone\n%s\n' "$QUOTE" >> "$d"
install_skill_context "$SRC" "$d" >/dev/null 2>&1           # quote exists BEFORE the first delivery
evolve_add "$d" EVOLVED-QUOTE-KEEPME
install_skill_context "$SRC" "$d" >/dev/null 2>&1
if fence_ok "$d" && getff_once "$d" && grep -qF EVOLVED-RULE-KEEPME "$d" && grep -qF EVOLVED-QUOTE-KEEPME "$d" \
   && grep -qxF -- "$QUOTE" "$d"; then
  ok "(6) marker quoted before the first delivery: block delivered once, every evolved rule kept"
else
  bad "(6) marker quoted before the first delivery: fence/getff $(count "$GETFF_LINE" "$d")x, evolved $(count EVOLVED-RULE-KEEPME "$d")/$(count EVOLVED-QUOTE-KEEPME "$d")"
fi
W=$(consumer); PROJECT_ROOT="$W"; d="$W/$SC_REL"
evolve_create "$d"; install_skill_context "$SRC" "$d" >/dev/null 2>&1
# evolve later inserts rules into ITS section, above getff's block; one quotes the marker
awk -v Q="$QUOTE" '/^### Null-check/ { print "### Leave the getff block alone"; print Q; print ""; print "### Tx"; print "**Rule**: EVOLVED-ABOVE-KEEPME one transaction per handler."; print "" } { print }' "$d" > "$d.x" && mv "$d.x" "$d"
# a stray line inside the real block proves the refresh re-delivered it rather than refusing
awk 'index($0, "<!-- getff:begin section=getff-skill-context plan=") == 1 { print; print "TAMPER-INSIDE-FENCE"; next } { print }' "$d" > "$d.x" && mv "$d.x" "$d"
install_skill_context "$SRC" "$d" >/dev/null 2>&1
if fence_ok "$d" && getff_once "$d" && grep -qF EVOLVED-RULE-KEEPME "$d" && grep -qF EVOLVED-ABOVE-KEEPME "$d" \
   && [ "$(count TAMPER-INSIDE-FENCE "$d")" = "0" ]; then
  ok "(6) marker quoted above an existing block: the refresh re-delivers the block and keeps every evolved rule"
else
  bad "(6) marker quoted above an existing block: evolved $(count EVOLVED-RULE-KEEPME "$d")/$(count EVOLVED-ABOVE-KEEPME "$d"), stale in-block line $(count TAMPER-INSIDE-FENCE "$d")x"
fi
# (6b) two WHOLE-LINE begin markers — which block is getff's cannot be told: refuse, touch nothing
W=$(consumer); PROJECT_ROOT="$W"; d="$W/$SC_REL"
install_skill_context "$SRC" "$d" >/dev/null 2>&1; evolve_add "$d" EVOLVED-DUP-KEEPME
head -n 3 "$d" > "$d.dup"; { cat "$d.dup"; echo "$END"; } >> "$d"; rm -f "$d.dup"
PRE=$(cat "$d"); ERR=$(install_skill_context "$SRC" "$d" 2>&1 >/dev/null)
if [ "$PRE" = "$(cat "$d")" ] && case "$ERR" in *REFUSING*) true ;; *) false ;; esac; then
  ok "(6b) two whole-line begin markers: refused loudly, file untouched"
else
  bad "(6b) two whole-line begin markers: file changed or no loud refusal"
fi

# (7) re-delivery over a block that still holds a body getff shipped → nothing parked, no warning;
#     over a block someone edited → the previous bytes parked under a skill-qualified name
W=$(consumer); PROJECT_ROOT="$W"; d="$W/$SC_REL"
OLDSRC=$(mktemp); cur=$(git -C "$REPO_ROOT" hash-object "$SRC")
for blob in $(history_blobs "$SRC_REL"); do [ "$blob" != "$cur" ] && git -C "$REPO_ROOT" cat-file -p "$blob" > "$OLDSRC"; done
evolve_create "$d"; install_skill_context "$OLDSRC" "$d" >/dev/null 2>&1
OUT=$(install_skill_context "$SRC" "$d" 2>&1)
if getff_once "$d" && ! ls "$W/.ai-factory/refresh-conflicts/"* >/dev/null 2>&1 && case "$OUT" in *⚠*) false ;; *) true ;; esac; then
  ok "(7) template update over a shipped body: replaced silently, nothing parked"
else
  bad "(7) template update over a shipped body: a copy was parked / a warning printed for bytes getff wrote"
fi
awk -v B="$BEG" 'index($0, B) == 1 { print; print "TAMPER-INSIDE-FENCE"; next } { print }' "$d" > "$d.x" && mv "$d.x" "$d"
install_skill_context "$SRC" "$d" >/dev/null 2>&1
if [ "$(count TAMPER-INSIDE-FENCE "$d")" = "0" ] && ls "$W/.ai-factory/refresh-conflicts/aif-review-SKILL.md."* >/dev/null 2>&1 \
   && ! ls "$W/.ai-factory/refresh-conflicts/SKILL.md."* >/dev/null 2>&1; then
  ok "(7) edited block: replaced, previous bytes parked as aif-review-SKILL.md.<sha8>"
else
  bad "(7) edited block: tamper kept, or the parked copy is missing / not skill-qualified: $(find "$W/.ai-factory/refresh-conflicts" -type f -exec basename {} \; 2>/dev/null | tr '\n' ' ')"
fi

# (8) markers stripped (an evolve rewrite dropped the HTML comments) → the bare getff block is
#     recognised and replaced by one fenced block — never duplicated beside it
W=$(consumer); PROJECT_ROOT="$W"; d="$W/$SC_REL"
evolve_create "$d"; install_skill_context "$SRC" "$d" >/dev/null 2>&1
grep -vF 'getff:begin section=getff-skill-context' "$d" | grep -vF 'getff:end section=getff-skill-context' > "$d.x" && mv "$d.x" "$d"
evolve_add "$d" EVOLVED-STRIPPED-KEEPME
install_skill_context "$SRC" "$d" >/dev/null 2>&1
if fence_ok "$d" && getff_once "$d" && grep -qF EVOLVED-RULE-KEEPME "$d" && grep -qF EVOLVED-STRIPPED-KEEPME "$d" \
   && [ "$(count '> Managed by getff:' "$d")" = "1" ]; then
  ok "(8) stripped markers: bare getff block replaced by one fenced block, evolved rules kept"
else
  bad "(8) stripped markers: template $(count "$GETFF_LINE" "$d")x, note $(count '> Managed by getff:' "$d")x, evolved $(count EVOLVED-RULE-KEEPME "$d")/$(count EVOLVED-STRIPPED-KEEPME "$d")"
fi

# ── §2 PAIRED NEGATIVE — the same predicates must catch the old whole-file verbs ──────────────
echo "── §2 paired negative (old whole-file verbs) ──"
W=$(consumer); PROJECT_ROOT="$W"
evolve_create "$W/$SC_REL"
copy_safe "$SRC" "$W/$SC_REL" >/dev/null 2>&1
getff_once "$W/$SC_REL" \
  && bad "neg: copy_safe onto an evolved file reads as delivered → predicate (1) is vacuous" \
  || ok "neg: copy_safe onto an evolved file is caught by predicate (1) (getff content absent)"
W=$(consumer); PROJECT_ROOT="$W"
mkdir -p "$(dirname "$W/$SC_REL")"; cp "$SRC" "$W/$SC_REL"; evolve_add "$W/$SC_REL" EVOLVED-NEG
refresh_safe "$SRC" "$W/$SC_REL" >/dev/null 2>&1
grep -qF EVOLVED-NEG "$W/$SC_REL" \
  && bad "neg: refresh_safe kept the evolved rule → predicate (2) is vacuous" \
  || ok "neg: refresh_safe wiping an evolved rule is caught by predicate (2)"

# ── §3 WIRING — the REAL installer, both lanes, install then --refresh ─────────────────────────
echo "── §3 wiring (real install.sh) ──"
wiring_arm() {  # $1 = lane label, $2 = fixture dir, $3.. = install.sh args
  local label="$1" T="$2"; shift 2
  local f="$T/$SC_REL"
  evolve_create "$f"
  local rc
  ( cd "$T" && git init -q && bash "$REPO_ROOT/install.sh" "$@" < /dev/null ) >/dev/null 2>&1; rc=$?
  [ "$rc" = 0 ] && ok "$label install: install.sh exited 0" || bad "$label install: install.sh exited $rc"
  if getff_once "$f" && fence_ok "$f" && grep -qF EVOLVED-RULE-KEEPME "$f"; then
    ok "$label install: evolved file kept AND getff's block delivered"
  else
    bad "$label install: getff content $(count "$GETFF_LINE" "$f")x, fence $(count "$BEG" "$f")x, evolved $(count EVOLVED-RULE-KEEPME "$f")x"
  fi
  evolve_add "$f" EVOLVED-AFTER-INSTALL
  # A line inside getff's block: a --refresh that really re-delivers the block must remove it —
  # without this, «evolved rules survive» would also hold for a refresh that never touched the file.
  awk -v B="$BEG" 'index($0, B) == 1 { print; print "TAMPER-INSIDE-FENCE"; next } { print }' "$f" > "$f.x" && mv "$f.x" "$f"
  ( cd "$T" && bash "$REPO_ROOT/install.sh" "$@" --refresh < /dev/null ) >/dev/null 2>&1; rc=$?
  [ "$rc" = 0 ] && ok "$label --refresh: install.sh exited 0" || bad "$label --refresh: install.sh exited $rc"
  if [ "$(count TAMPER-INSIDE-FENCE "$f")" = "0" ] && grep -qF EVOLVED-RULE-KEEPME "$f" \
     && grep -qF EVOLVED-AFTER-INSTALL "$f" && getff_once "$f" && fence_ok "$f"; then
    ok "$label --refresh: getff's block re-delivered, every evolved rule still in the live file"
  else
    bad "$label --refresh: tamper $(count TAMPER-INSIDE-FENCE "$f")x, evolved $(count EVOLVED-RULE-KEEPME "$f")/$(count EVOLVED-AFTER-INSTALL "$f"), getff $(count "$GETFF_LINE" "$f")x"
  fi
}
T=$(mktemp -d); printf '{"name":"sc","version":"0.0.0"}\n' > "$T/package.json"
wiring_arm "npm lane (ts-server)" "$T" ts-server
T=$(mktemp -d); printf '[project]\nname = "sc"\nversion = "0.0.1"\n' > "$T/pyproject.toml"
wiring_arm "python lane" "$T" python

echo ""; echo "PASS=$PASS FAIL=$FAIL"; [ "$FAIL" -eq 0 ]
