// ruff.toml renderer — flake8-tidy-imports fast-path — MT umbrella S2 (python-backend-v0).
// Spec: docs/superpowers/specs/2026-07-03-multi-toolchain-convention-compiler-design.md §4 (RenderOutcome), §7.
// Prior-art: docs/meta-factory/prior-art-evaluations.md#215 (ruff TID fast-path, ADOPT narrow).
//
// Pure function: zero fs/network access. Does NOT run the grammar gate itself (planes separated —
// the grammar gate is an IR-plane concern; this is the backend-render plane), mirroring
// backends/{cargo,astgrep}/render-*.ts.
//
// WHY NARROW (P2 census NO-GO, research-patches/2026-07-02-multi-toolchain-generalization.md:363-378):
// ruff's *custom-rule* surface is the CLOSED flake8-tidy-imports vocabulary — TID251 banned-api
// (qualified-name / API ban) + TID253 banned-module-level-imports (module-level import ban). It has
// NO custom-AST-rule surface, so it can express ONLY import / qualified-name bans. The Python census
// native drop is 90.9%/100% — far above the 50-70% "product death" band — so Python enters via the
// ast-grep escape hatch by DEFAULT (render-astgrep.ts, #212), and this backend is retained purely as
// a FAST-PATH for the 2 import/qualified-name bans ast-grep would otherwise also handle. Do NOT grow
// the fast-path (T-PY-B): everything outside it refuses honestly, ast-grep is the catch-all.
//
// PARAMS CONTRACT — shared IR node with the astgrep backend (backends/astgrep/render-astgrep.ts):
//   { kind: 'call' | 'attribute' | 'import', pattern: string, replacement?: string }
// A node bannable by BOTH backends must route on both. The kind -> ruff-table mapping mirrors how
// astgrep's params express the same ban on the shared node:
//   - kind 'import'    (astgrep: `import <mod>` pattern)      -> ruff TID253 banned-module-level-imports
//                        (the module name is extracted from the `import <dotted>` pattern)
//   - kind 'attribute' (astgrep: attribute-chain `a.b.c`)    -> ruff TID251 banned-api (qualified-name key)
//   - kind 'call'      (astgrep: `a.b.c($$$ARGS)` call site) -> NOT in the fast-path -> refused FF7001:
//                        ruff bans a qualified NAME, it cannot express a call-site arg pattern
//                        (`$$$ARGS`); the call-only semantics are inexpressible -> astgrep catch-all.
//
// ROUTING (exhaustive — every node resolves to exactly one RenderOutcome):
//   selectorClass 'type-aware'                            -> refused FF7001 (mypy backend deferred)
//   selectorClass 'dep-graph'                             -> refused FF7001 (import-linter deferred)
//   selectorClass 'syntax', kind 'call'                  -> refused FF7001 (out of fast-path)
//   selectorClass 'syntax', off-contract / malformed params -> refused FF7002
//   selectorClass 'syntax', kind 'import'|'attribute'    -> rendered | degraded (by severity)
//
// SEVERITY (FIRST backend in the Python lane to exercise FF7003): ruff has NO per-rule severity
// config (s0-verified-facts: `[lint.severity]` is rejected as an unknown field; the JSON `severity`
// is always "error"). So error IS ruff's fixed native level -> requested 'error' renders faithfully;
// a requested 'warning'/'note' cannot be projected -> degraded FF7003 (rendered-with-loss, the entry
// is STILL emitted — "nothing silent, including severity loss on ruff", spec §4). Contrast the cargo
// backend, whose fixed level is 'warning' (so IT degrades error/note), and the astgrep backend, which
// carries native per-rule severity (so it NEVER degrades).
//
// Known bound (documented, NOT a degrade): TID253 banned-module-level-imports is a plain string array
// with no per-entry message, so node.claim is NOT carried into a TID253 entry — ruff supplies its own
// standard message ("`<mod>` is banned at the module level", live-verified). This is not silent: the
// rule identity + firing evidence carry the ban; the claim lives in the codified rule. TID251 banned-api
// DOES carry node.claim via `.msg` (live-verified: "`requests` is banned: <claim>").

import { diag } from '../../diagnostics/registry.ts';
import type { ConventionNode } from '../../ir/types.ts';
import { assertEveryNodeResolved, type RenderOutcome } from '../shared/render-outcome.ts';
import type { ToolchainBackend } from '../shared/toolchain-backend.ts';

type BackendParamKind = 'call' | 'attribute' | 'import';

const VALID_KINDS: readonly string[] = ['call', 'attribute', 'import'];

const BACKEND_NAME = 'ruff-tidy-imports-toml';

// A ruff banned-module-level-imports name / banned-api key is a dotted Python identifier
// (`requests`, `datetime.datetime.now`). Parens / metavariables / spaces are NOT a qualified name.
const DOTTED_NAME = /^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/;

const HEADER = '# generated by getff ruff backend v0 — do not edit by hand';

function paramStr(params: Record<string, string | number>, key: string): string | undefined {
  const v = params[key];
  return typeof v === 'string' ? v : undefined;
}

/** Extract the dotted name a ruff table entry needs from the shared-IR `pattern`, per kind. */
function extractName(kind: 'attribute' | 'import', pattern: string): string | undefined {
  if (kind === 'attribute') {
    return DOTTED_NAME.test(pattern) ? pattern : undefined;
  }
  // kind === 'import': accept `import <dotted>` (astgrep's import pattern) or a bare dotted name.
  const stripped = pattern.startsWith('import ') ? pattern.slice('import '.length).trim() : pattern;
  return DOTTED_NAME.test(stripped) ? stripped : undefined;
}

/** Escape a TOML basic string (backslash + double-quote). */
function escapeTomlString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

interface BanApiEntry {
  key: string; // qualified name (TID251 banned-api key)
  msg: string; // node.claim
}

/**
 * Render a set of ConventionNode into a ruff.toml (v0: flake8-tidy-imports fast-path —
 * TID251 banned-api + TID253 banned-module-level-imports) plus a per-node RenderOutcome map.
 * The artifact is a single string — the content of one `ruff.toml` config file.
 */
export function renderRuff(nodes: ConventionNode[]): { toml: string; outcomes: Map<string, RenderOutcome> } {
  const outcomes = new Map<string, RenderOutcome>();
  const bannedModules: string[] = []; // TID253
  const bannedApi: BanApiEntry[] = []; // TID251

  for (const n of nodes) {
    // --- capability-class refusals (FF7001) — the two semantic classes ruff cannot serve. ---
    if (n.selectorClass === 'type-aware' || n.selectorClass === 'dep-graph') {
      const note =
        n.selectorClass === 'type-aware'
          ? 'type-aware bans need a type checker; route to the mypy backend (deferred, post-v0)'
          : 'dependency-graph bans need import analysis; route to the import-linter backend (deferred, post-v0)';
      outcomes.set(n.id, { kind: 'refused', code: 'FF7001', note });
      diag('FF7001', { backend: BACKEND_NAME, selectorClass: n.selectorClass, nodeId: n.id });
      continue;
    }

    // selectorClass === 'syntax' from here on (the only remaining CapabilityClass).
    const kind = paramStr(n.params, 'kind');
    const pattern = paramStr(n.params, 'pattern');

    // --- params-contract refusals (FF7002): missing/invalid kind, or empty/missing pattern. ---
    if (kind === undefined || !VALID_KINDS.includes(kind)) {
      outcomes.set(n.id, { kind: 'refused', code: 'FF7002', note: 'params contract violation: missing/invalid kind' });
      diag('FF7002', { backend: BACKEND_NAME, nodeId: n.id, missing: 'kind' });
      continue;
    }
    if (pattern === undefined || pattern.length === 0) {
      outcomes.set(n.id, { kind: 'refused', code: 'FF7002', note: 'params contract violation: missing/invalid pattern' });
      diag('FF7002', { backend: BACKEND_NAME, nodeId: n.id, missing: 'pattern' });
      continue;
    }

    // --- capability-gap refusal (FF7001): a call-with-args ban is OUT of the fast-path. ---
    // ruff bans a qualified NAME, not a call site — the `$$$ARGS` semantics are inexpressible.
    // This is a capability gap (astgrep catch-all), NOT a params error: the params are well-formed.
    if ((kind as BackendParamKind) === 'call') {
      outcomes.set(n.id, {
        kind: 'refused',
        code: 'FF7001',
        note: 'call-with-args ban not expressible in ruff (bans a qualified name, not a call site); route to the ast-grep backend (#212)',
      });
      diag('FF7001', { backend: BACKEND_NAME, selectorClass: n.selectorClass, nodeId: n.id });
      continue;
    }

    // kind is 'attribute' | 'import' — extract the dotted name the ruff table needs.
    const name = extractName(kind as 'attribute' | 'import', pattern);
    if (name === undefined) {
      outcomes.set(n.id, {
        kind: 'refused',
        code: 'FF7002',
        note: `params contract violation: pattern is not a qualified name for kind ${kind}`,
      });
      diag('FF7002', { backend: BACKEND_NAME, nodeId: n.id, missing: 'pattern' });
      continue;
    }

    // Emit the entry (degraded = rendered-with-loss: the entry is added regardless of severity).
    if ((kind as BackendParamKind) === 'import') {
      bannedModules.push(name);
    } else {
      bannedApi.push({ key: name, msg: n.claim }); // msg is ALWAYS node.claim (spec §4 parity).
    }

    // --- severity projection: 'error' is ruff's fixed native level; anything lower degrades FF7003. ---
    if (n.defaultSeverity === 'error') {
      outcomes.set(n.id, { kind: 'rendered', surfaces: [{ surface: 'rule', content: n.id }] });
    } else {
      outcomes.set(n.id, {
        kind: 'degraded',
        code: 'FF7003',
        note: 'ruff has no per-rule severity; diagnostics are fixed at error level, requested severity not projected',
      });
      diag('FF7003', { backend: BACKEND_NAME, nodeId: n.id, requested: n.defaultSeverity });
    }
  }

  assertEveryNodeResolved(
    nodes.map((n) => n.id),
    outcomes,
  );

  const toml = renderToml(bannedModules, bannedApi);
  return { toml, outcomes };
}

// ToolchainBackend<string> conformance. The public renderRuff keeps its `{ toml, outcomes }` shape;
// this adapts it to the generic `{ artifacts, outcomes }` frame (its artifact is the TOML string),
// mirroring cargoClippyBackend / astgrepBackend.
export const ruffBackend = {
  name: BACKEND_NAME,
  render(nodes: ConventionNode[]) {
    const { toml, outcomes } = renderRuff(nodes);
    return { artifacts: toml, outcomes };
  },
} satisfies ToolchainBackend<string>;

function renderToml(bannedModules: string[], bannedApi: BanApiEntry[]): string {
  const lines: string[] = [HEADER];

  // No fast-path entry rendered -> header-only file (parity with cargo/astgrep header-only emission).
  if (bannedModules.length === 0 && bannedApi.length === 0) {
    return lines.join('\n') + '\n';
  }

  // [lint] select — only the codes that actually have entries, sorted for determinism.
  const codes: string[] = [];
  if (bannedApi.length > 0) codes.push('TID251');
  if (bannedModules.length > 0) codes.push('TID253');
  codes.sort();
  lines.push('[lint]');
  lines.push(`select = [${codes.map((c) => `"${c}"`).join(', ')}]`);

  // TID253 — banned-module-level-imports (sorted, then deduped: two nodes banning the same module
  // would otherwise emit the same string twice in the array — harmless-but-noisy — so collapse to a
  // stable set). Sort-first makes dupes adjacent; the Set preserves that sorted order.
  if (bannedModules.length > 0) {
    const sorted = [...new Set([...bannedModules].sort((a, b) => a.localeCompare(b)))];
    lines.push('');
    lines.push('[lint.flake8-tidy-imports]');
    lines.push(`banned-module-level-imports = [${sorted.map((m) => `"${escapeTomlString(m)}"`).join(', ')}]`);
  }

  // TID251 — banned-api (sorted by qualified-name key, then deduped BY KEY). Two nodes banning the
  // same qualified name would emit the same `"<key>".msg` TOML key twice = INVALID TOML (duplicate
  // key). Collapse to one entry per key, keeping the first (post-sort) occurrence's message.
  if (bannedApi.length > 0) {
    const sorted = [...bannedApi].sort((a, b) => a.key.localeCompare(b.key));
    const seen = new Set<string>();
    const deduped = sorted.filter((e) => (seen.has(e.key) ? false : (seen.add(e.key), true)));
    lines.push('');
    lines.push('[lint.flake8-tidy-imports.banned-api]');
    for (const e of deduped) {
      lines.push(`"${escapeTomlString(e.key)}".msg = "${escapeTomlString(e.msg)}"`);
    }
  }

  return lines.join('\n') + '\n';
}
