// ast-grep YAML renderer — paired negatives (MT umbrella S1, astgrep-backend-v0).
// Spec: docs/superpowers/specs/2026-07-03-multi-toolchain-convention-compiler-design.md §3, §4.
// RED-first: authored BEFORE render-astgrep.ts — run to confirm it fails to import/compile,
// then implement until every case below is GREEN. Mirrors backends/cargo/render-clippy.test.ts.

import { describe, expect, it } from 'vitest';
import type { ConventionNode, RelationalRule } from '../../ir/types.ts';
import { runGrammarGate } from '../../ir/gates/grammar.ts';
import { assertEveryNodeResolved, type RenderOutcome } from '../shared/render-outcome.ts';
import { renderAstgrep } from './render-astgrep.ts';
import { FIXTURE_NODE, RELATIONAL_FIXTURE_NODE } from './test-fixtures.ts';

function node(overrides: Partial<ConventionNode> = {}): ConventionNode {
  return { ...FIXTURE_NODE, ...overrides };
}

describe('renderAstgrep — cross-stage self-application (T15)', () => {
  it('T15: FIXTURE_NODE is grammar-gate valid (pass) before it is used as a render fixture', () => {
    const outcome = runGrammarGate([FIXTURE_NODE]);
    expect(outcome.status).toBe('pass');
  });

  it('T15-relational: RELATIONAL_FIXTURE_NODE is grammar-gate valid (pass) before use as a render fixture', () => {
    const outcome = runGrammarGate([RELATIONAL_FIXTURE_NODE]);
    expect(outcome.status).toBe('pass');
  });
});

describe('renderAstgrep — paired negatives (routing; inverse of cargo)', () => {
  it('R1: selectorClass "type-aware" -> refused FF7001 (mypy deferred)', () => {
    const n = node({ id: 'r1', selectorClass: 'type-aware', params: {} });
    const { outcomes } = renderAstgrep([n]);
    const outcome = outcomes.get('r1');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7001');
  });

  it('R2: selectorClass "dep-graph" -> refused FF7001 (import-linter deferred)', () => {
    const n = node({ id: 'r2', selectorClass: 'dep-graph', params: {} });
    const { outcomes } = renderAstgrep([n]);
    const outcome = outcomes.get('r2');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7001');
  });

  it('R3: syntax params without pattern -> refused FF7002', () => {
    const n = node({ id: 'r3', params: { kind: 'call' } });
    const { outcomes } = renderAstgrep([n]);
    const outcome = outcomes.get('r3');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7002');
  });

  it('R3b: syntax params with empty-string pattern -> refused FF7002 (guards the length check)', () => {
    const n = node({ id: 'r3b', params: { kind: 'call', pattern: '' } });
    const { outcomes } = renderAstgrep([n]);
    const outcome = outcomes.get('r3b');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7002');
  });

  it('R4: syntax params kind "decorator" (off-contract) -> refused FF7002', () => {
    const n = node({ id: 'r4', params: { kind: 'decorator', pattern: 'foo.bar()' } });
    const { outcomes } = renderAstgrep([n]);
    const outcome = outcomes.get('r4');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7002');
  });

  it('P5: FIXTURE_NODE (syntax, error severity) -> rendered, yaml byte-for-byte == golden', () => {
    const { yaml, outcomes } = renderAstgrep([FIXTURE_NODE]);
    const outcome = outcomes.get('no-datetime-now');
    expect(outcome?.kind).toBe('rendered');
    const golden =
      '# generated by getff astgrep backend v0 — do not edit by hand\n' +
      'id: "no-datetime-now"\n' +
      'language: python\n' +
      'severity: error\n' +
      'message: "Use an injected clock, not datetime.datetime.now() directly"\n' +
      'metadata:\n' +
      '  kind: call\n' +
      'rule:\n' +
      '  pattern: "datetime.datetime.now($$$ARGS)"\n';
    expect(yaml).toBe(golden);
  });

  it('R5: severity is projected DIRECTLY (no FF7003) — warning renders as severity: warning', () => {
    const n = node({ id: 'no-datetime-now', defaultSeverity: 'warning' });
    const { yaml, outcomes } = renderAstgrep([n]);
    const outcome = outcomes.get('no-datetime-now');
    // Native per-rule severity: still 'rendered', NEVER 'degraded'/FF7003 (contrast cargo).
    expect(outcome?.kind).toBe('rendered');
    expect(yaml).toContain('severity: warning');
  });

  it('R5b: severity "note" projects to ast-grep "hint", still rendered (no FF7003)', () => {
    const n = node({ id: 'no-datetime-now', defaultSeverity: 'note' });
    const { yaml, outcomes } = renderAstgrep([n]);
    expect(outcomes.get('no-datetime-now')?.kind).toBe('rendered');
    expect(yaml).toContain('severity: hint');
  });

  it('R6: outcomes missing a node -> assertEveryNodeResolved throws', () => {
    const outcomes = new Map<string, RenderOutcome>();
    expect(() => assertEveryNodeResolved(['missing-1'], outcomes)).toThrow();
  });
});

describe('renderAstgrep — YAML shape', () => {
  it('message is ALWAYS node.claim (parity with render-clippy.ts:112), never a params field', () => {
    const n = node({ id: 'no-datetime-now', claim: 'Never sleep in request handlers' });
    const { yaml } = renderAstgrep([n]);
    expect(yaml).toContain('message: "Never sleep in request handlers"');
  });

  it('kind is carried into the rule metadata block', () => {
    const n = node({ id: 'no-requests', params: { kind: 'import', pattern: 'import requests' } });
    const { yaml } = renderAstgrep([n]);
    expect(yaml).toContain('  kind: import');
    expect(yaml).toContain('  pattern: "import requests"');
  });

  it('replacement param, when present, is emitted as a top-level fix', () => {
    const n = node({
      id: 'no-datetime-now',
      params: { kind: 'call', pattern: 'datetime.datetime.now($$$ARGS)', replacement: 'clock.now()' },
    });
    const { yaml } = renderAstgrep([n]);
    expect(yaml).toContain('fix: "clock.now()"');
  });

  it('multiple rendered nodes are sorted by id and separated by a --- document break', () => {
    const nb = node({ id: 'zzz-last', params: { kind: 'call', pattern: 'os.system($$$A)' } });
    const na = node({ id: 'aaa-first', params: { kind: 'call', pattern: 'eval($$$A)' } });
    const { yaml } = renderAstgrep([nb, na]);
    expect(yaml).toContain('\n---\n');
    const idxFirst = yaml.indexOf('aaa-first');
    const idxLast = yaml.indexOf('zzz-last');
    expect(idxFirst).toBeGreaterThan(-1);
    expect(idxLast).toBeGreaterThan(-1);
    expect(idxFirst).toBeLessThan(idxLast);
  });

  it('double quotes in the claim are escaped in the YAML message scalar', () => {
    const n = node({ id: 'no-datetime-now', claim: 'Use "the clock" accessor' });
    const { yaml } = renderAstgrep([n]);
    expect(yaml).toContain('message: "Use \\"the clock\\" accessor"');
  });
});

// OWNER-FORK-1 Option B (ir-unfreeze S2): renderRelationalArm translation. Each golden below was
// captured by running the ACTUAL renderAstgrep() output and then live-fired against real
// ast-grep 0.44.1 to confirm the intended relational semantics (NOR for multi-child `not`,
// AND for `all`, OR for `any`) — not just that the YAML parses. See render-astgrep.ts's
// renderRelationalNode doc comment for the rationale (stopBy:end, not:{any} not not:{all}).
describe('renderAstgrep — relational arm translation (byte-for-byte goldens)', () => {
  const HEADER = '# generated by getff astgrep backend v0 — do not edit by hand\n';
  const BASE_HEAD =
    'id: "sample"\n' +
    'language: python\n' +
    'severity: error\n' +
    'message: "sample claim"\n' +
    'metadata:\n' +
    '  kind: call\n' +
    'rule:\n' +
    '  pattern: "ANCHOR($$$A)"\n';

  function sampleNode(relational: RelationalRule): ConventionNode {
    return {
      id: 'sample',
      claim: 'sample claim',
      anchors: [],
      selectorClass: 'syntax',
      params: { kind: 'call', pattern: 'ANCHOR($$$A)' },
      relational,
      defaultSeverity: 'error',
      provenance: [],
      pairedExamples: { positive: 'p', negative: 'n' },
    };
  }

  it('legacy scalar node (no relational field) renders with NO relational lines — byte-lock unaffected', () => {
    const { yaml } = renderAstgrep([FIXTURE_NODE]);
    expect(yaml).not.toContain('not:');
    expect(yaml).not.toContain('has:');
    expect(yaml).not.toContain('stopBy');
  });

  it('has: emits kind (when present) then pattern then stopBy:end, nested under the leaf', () => {
    const { yaml } = renderAstgrep([sampleNode({ op: 'has', kind: 'call', pattern: 'x' })]);
    expect(yaml).toBe(
      HEADER +
        BASE_HEAD +
        '  has:\n' +
        '    kind: call\n' +
        '    pattern: "x"\n' +
        '    stopBy: end\n',
    );
  });

  it('has: without kind omits the kind line entirely (optional field, not emitted as blank)', () => {
    const { yaml } = renderAstgrep([sampleNode({ op: 'has', pattern: 'x' })]);
    expect(yaml).toBe(HEADER + BASE_HEAD + '  has:\n' + '    pattern: "x"\n' + '    stopBy: end\n');
  });

  it('not (1 child) -> `not:` then nested render(child), 1:1 native not:{has:...} (census require-via-ban shape)', () => {
    const { yaml } = renderAstgrep([
      sampleNode({ op: 'not', children: [{ op: 'has', pattern: 'x' }] }),
    ]);
    expect(yaml).toBe(
      HEADER + BASE_HEAD + '  not:\n' + '    has:\n' + '      pattern: "x"\n' + '      stopBy: end\n',
    );
  });

  it('not (2 children) -> NOR -> not:{any:[...]}, NEVER not:{all:[...]} (live-verified semantics)', () => {
    const { yaml } = renderAstgrep([
      sampleNode({
        op: 'not',
        children: [
          { op: 'has', pattern: 'x' },
          { op: 'has', kind: 'call', pattern: 'y' },
        ],
      }),
    ]);
    expect(yaml).toBe(
      HEADER +
        BASE_HEAD +
        '  not:\n' +
        '    any:\n' +
        '      - has:\n' +
        '          pattern: "x"\n' +
        '          stopBy: end\n' +
        '      - has:\n' +
        '          kind: call\n' +
        '          pattern: "y"\n' +
        '          stopBy: end\n',
    );
    expect(yaml).not.toContain('all:');
  });

  it('all (2 children) -> `all:` block-sequence, each item a rendered child (conjunction)', () => {
    const { yaml } = renderAstgrep([
      sampleNode({
        op: 'all',
        children: [
          { op: 'has', pattern: 'x' },
          { op: 'has', pattern: 'y' },
        ],
      }),
    ]);
    expect(yaml).toBe(
      HEADER +
        BASE_HEAD +
        '  all:\n' +
        '    - has:\n' +
        '        pattern: "x"\n' +
        '        stopBy: end\n' +
        '    - has:\n' +
        '        pattern: "y"\n' +
        '        stopBy: end\n',
    );
  });

  it('any (2 children) -> `any:` block-sequence, each item a rendered child (disjunction)', () => {
    const { yaml } = renderAstgrep([
      sampleNode({
        op: 'any',
        children: [
          { op: 'has', pattern: 'x' },
          { op: 'has', pattern: 'y' },
        ],
      }),
    ]);
    expect(yaml).toBe(
      HEADER +
        BASE_HEAD +
        '  any:\n' +
        '    - has:\n' +
        '        pattern: "x"\n' +
        '        stopBy: end\n' +
        '    - has:\n' +
        '        pattern: "y"\n' +
        '        stopBy: end\n',
    );
  });

  it('nested composite (not wrapping all) recurses indentation correctly', () => {
    const { yaml } = renderAstgrep([
      sampleNode({
        op: 'not',
        children: [
          {
            op: 'all',
            children: [
              { op: 'has', pattern: 'x' },
              { op: 'has', pattern: 'y' },
            ],
          },
        ],
      }),
    ]);
    expect(yaml).toBe(
      HEADER +
        BASE_HEAD +
        '  not:\n' +
        '    all:\n' +
        '      - has:\n' +
        '          pattern: "x"\n' +
        '          stopBy: end\n' +
        '      - has:\n' +
        '          pattern: "y"\n' +
        '          stopBy: end\n',
    );
  });

  it('P-relational: RELATIONAL_FIXTURE_NODE renders byte-for-byte == committed require-return-type-hint.yml golden', () => {
    const { yaml, outcomes } = renderAstgrep([RELATIONAL_FIXTURE_NODE]);
    expect(outcomes.get('require-return-type-hint')?.kind).toBe('rendered');
    const golden =
      HEADER +
      'id: "require-return-type-hint"\n' +
      'language: python\n' +
      'severity: error\n' +
      'message: "Add a return type hint to every function definition"\n' +
      'metadata:\n' +
      '  kind: call\n' +
      'rule:\n' +
      '  pattern: "def $NAME($$$ARGS)$$$TAIL: $$$BODY"\n' +
      '  not:\n' +
      '    has:\n' +
      '      kind: type\n' +
      '      pattern: "$T"\n' +
      '      stopBy: end\n';
    expect(yaml).toBe(golden);
  });
});
