// ast-grep YAML rule-set renderer — MT umbrella S1 (python-backend-v0, astgrep-backend-v0).
// Spec: docs/superpowers/specs/2026-07-03-multi-toolchain-convention-compiler-design.md §3 (node), §4 (RenderOutcome).
// Prior-art: docs/meta-factory/prior-art-evaluations.md#212 (ast-grep as Python rule-emission target, ADOPT).
//
// Pure function: zero fs/network access. Does NOT run the grammar gate itself (planes
// separated — the grammar gate is an IR-plane concern; this is the backend-render plane),
// mirroring backends/cargo/render-clippy.ts.
//
// Routing (exhaustive — every node resolves to exactly one RenderOutcome). NOTE the routing
// is the INVERSE of the cargo backend: ast-grep is a structural/syntax matcher, so the syntax
// class is the RENDERED one here and the two semantic classes refuse:
//   selectorClass 'syntax', valid params   -> rendered (native per-rule severity, NO FF7003)
//   selectorClass 'syntax', off-contract params -> refused FF7002
//   selectorClass 'type-aware'              -> refused FF7001 (mypy backend deferred)
//   selectorClass 'dep-graph'               -> refused FF7001 (import-linter backend deferred)
//
// Severity: ast-grep carries native per-rule severity (`severity:` in the rule YAML), so the
// node's defaultSeverity is projected DIRECTLY — there is no FF7003 degrade path on this
// backend (contrast render-clippy.ts, where clippy.toml carries no severity). Verified live
// against @ast-grep/cli@0.44.1 (s0-verified-facts): `severity: error` on the rendered rule
// yields exit 1 + `severity: "error"` in `scan --json`.
//
// Known bound (NOT statically detected by this v0 renderer — the honesty boundary lives in the
// capability-matrix cell's evidence + firing fixtures, not here): v0 emits the caller-supplied
// `pattern` verbatim for all three `kind`s. `kind` is a validated discriminator carried into
// the rule's `metadata` block; it does not yet specialise the emitted `rule:` shape (e.g. an
// `import` kind could compile to an ast-grep relational rule post-v0). Analogous to the cargo
// renderer carrying `kind` into the table choice.

import { diag } from '../../diagnostics/registry.ts';
import type { Severity } from '../../diagnostics/types.ts';
import type { ConventionNode } from '../../ir/types.ts';
import { assertEveryNodeResolved, type RenderOutcome } from '../shared/render-outcome.ts';
import type { ToolchainBackend } from '../shared/toolchain-backend.ts';

type BackendParamKind = 'call' | 'attribute' | 'import';

interface AstgrepBackendParams {
  kind: BackendParamKind;
  pattern: string;
  replacement?: string;
}

// Exported so upstream authors (e.g. the research-to-node bridge's EXPRESSIBLE_KINDS) can assert
// set-equality against the ONE accepted-kind list — a drift where a kind is added to the bridge but
// not here (node builds, then FF7002-refuses) is then caught by a test, not at render time.
export const VALID_KINDS: readonly string[] = ['call', 'attribute', 'import'];

const BACKEND_NAME = 'astgrep-python-yaml';

// ast-grep severity vocabulary (hint|info|warning|error|off); our Severity is
// 'error'|'warning'|'note'. 'note' has no direct ast-grep peer -> 'hint' (the lowest
// non-off level). error/warning map identity. This is a direct projection, NOT a degrade:
// every syntax-class node renders with its requested severity, no FF7003.
const SEVERITY_TO_ASTGREP: Record<Severity, string> = {
  error: 'error',
  warning: 'warning',
  note: 'hint',
};

function isValidParams(
  params: Record<string, string | number>,
): params is AstgrepBackendParams & Record<string, string | number> {
  const kind = params['kind'];
  const pattern = params['pattern'];
  if (typeof kind !== 'string' || !VALID_KINDS.includes(kind)) return false;
  if (typeof pattern !== 'string' || pattern.length === 0) return false;
  return true;
}

function missingOrInvalidField(params: Record<string, string | number>): string {
  const kind = params['kind'];
  if (typeof kind !== 'string' || !VALID_KINDS.includes(kind)) return 'kind';
  const pattern = params['pattern'];
  if (typeof pattern !== 'string' || pattern.length === 0) return 'pattern';
  return 'unknown';
}

/** Escape a string for a YAML double-quoted scalar (backslash + double-quote). */
function yamlDq(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

interface RuleEntry {
  id: string;
  severity: string;
  message: string; // ALWAYS node.claim (spec §4 parity with render-clippy.ts:112)
  kind: BackendParamKind;
  pattern: string;
  replacement?: string;
}

const HEADER = '# generated by getff astgrep backend v0 — do not edit by hand';

/**
 * Render a set of ConventionNode into an ast-grep YAML rule-set (one YAML document per
 * rendered rule, `---`-separated, sorted by node id for determinism) plus a per-node
 * RenderOutcome map. The artifact is a single string — the content of one rule file that
 * `ast-grep scan` reads under a `ruleDirs:` layout.
 */
export function renderAstgrep(nodes: ConventionNode[]): { yaml: string; outcomes: Map<string, RenderOutcome> } {
  const outcomes = new Map<string, RenderOutcome>();
  const entries: RuleEntry[] = [];

  for (const n of nodes) {
    if (n.selectorClass === 'type-aware' || n.selectorClass === 'dep-graph') {
      const note =
        n.selectorClass === 'type-aware'
          ? 'type-aware bans need a type checker; route to the mypy backend (deferred, post-v0)'
          : 'dependency-graph bans need import analysis; route to the import-linter backend (deferred, post-v0)';
      outcomes.set(n.id, { kind: 'refused', code: 'FF7001', note });
      diag('FF7001', { backend: BACKEND_NAME, selectorClass: n.selectorClass, nodeId: n.id });
      continue;
    }

    // selectorClass === 'syntax' from here on (the only remaining CapabilityClass).
    if (!isValidParams(n.params)) {
      const missing = missingOrInvalidField(n.params);
      outcomes.set(n.id, {
        kind: 'refused',
        code: 'FF7002',
        note: `params contract violation: missing/invalid ${missing}`,
      });
      diag('FF7002', { backend: BACKEND_NAME, nodeId: n.id, missing });
      continue;
    }

    const params = n.params as unknown as AstgrepBackendParams;
    entries.push({
      id: n.id,
      severity: SEVERITY_TO_ASTGREP[n.defaultSeverity],
      message: n.claim, // message is ALWAYS node.claim — params carry no message (spec §4).
      kind: params.kind,
      pattern: params.pattern,
      ...(params.replacement !== undefined ? { replacement: params.replacement } : {}),
    });
    // Native per-rule severity — the requested severity IS projected, so this is 'rendered',
    // never 'degraded'. The 'rule' surface content is the node id (its rule document).
    outcomes.set(n.id, { kind: 'rendered', surfaces: [{ surface: 'rule', content: n.id }] });
  }

  assertEveryNodeResolved(
    nodes.map((n) => n.id),
    outcomes,
  );

  const yaml = renderYaml(entries);
  return { yaml, outcomes };
}

// ToolchainBackend<string> conformance. The public renderAstgrep is NOT renamed and keeps its
// `{ yaml, outcomes }` shape; this declaration adapts it to the generic `{ artifacts, outcomes }`
// frame (its artifact is the YAML string), mirroring cargoClippyBackend.
export const astgrepBackend = {
  name: BACKEND_NAME,
  render(nodes: ConventionNode[]) {
    const { yaml, outcomes } = renderAstgrep(nodes);
    return { artifacts: yaml, outcomes };
  },
} satisfies ToolchainBackend<string>;

function renderRule(e: RuleEntry): string {
  const lines = [
    `id: ${yamlDq(e.id)}`,
    'language: python',
    `severity: ${e.severity}`,
    `message: ${yamlDq(e.message)}`,
    'metadata:',
    `  kind: ${e.kind}`,
    'rule:',
    `  pattern: ${yamlDq(e.pattern)}`,
  ];
  if (e.replacement !== undefined) {
    lines.push(`fix: ${yamlDq(e.replacement)}`);
  }
  return lines.join('\n');
}

function renderYaml(entries: RuleEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id));
  const docs = [HEADER + '\n' + sorted.map(renderRule).join('\n---\n')];
  // If there are zero rendered rules, still emit the header alone (parity with render-clippy.ts
  // emitting the header-only TOML when no table has entries).
  const body = sorted.length === 0 ? HEADER : docs[0];
  return body + '\n';
}
