// cargo clippy.toml renderer — paired negatives (MT umbrella S2, cargo-backend-v0).
// Spec: docs/superpowers/specs/2026-07-03-multi-toolchain-convention-compiler-design.md §4, §7.
// RED-first: this file is authored BEFORE render-clippy.ts exists — run to confirm it fails
// to import/compile, then implement until every case below is GREEN.

import { describe, expect, it } from 'vitest';
import type { ConventionNode } from '../../ir/types.ts';
import { runGrammarGate } from '../../ir/gates/grammar.ts';
import { assertEveryNodeResolved, type RenderOutcome } from '../shared/render-outcome.ts';
import { renderCargoClippy } from './render-clippy.ts';
import { FIXTURE_NODE } from './test-fixtures.ts';

function node(overrides: Partial<ConventionNode> = {}): ConventionNode {
  return { ...FIXTURE_NODE, ...overrides };
}

describe('renderCargoClippy — cross-stage self-application (T15)', () => {
  it('T15: FIXTURE_NODE is grammar-gate valid (pass) before it is used as a render fixture', () => {
    const outcome = runGrammarGate([FIXTURE_NODE]);
    expect(outcome.status).toBe('pass');
  });
});

describe('renderCargoClippy — paired negatives (routing)', () => {
  it('R1: selectorClass "syntax" -> refused FF7001', () => {
    const n = node({ id: 'r1', selectorClass: 'syntax', params: {} });
    const { outcomes } = renderCargoClippy([n]);
    const outcome = outcomes.get('r1');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7001');
  });

  it('R2: selectorClass "dep-graph" -> refused FF7001', () => {
    const n = node({ id: 'r2', selectorClass: 'dep-graph', params: {} });
    const { outcomes } = renderCargoClippy([n]);
    const outcome = outcomes.get('r2');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7001');
  });

  it('R3: type-aware params without path -> refused FF7002', () => {
    const n = node({ id: 'r3', params: { kind: 'method' } });
    const { outcomes } = renderCargoClippy([n]);
    const outcome = outcomes.get('r3');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7002');
  });

  it('R4: type-aware params kind "trait-impl" (off-contract) -> refused FF7002', () => {
    const n = node({ id: 'r4', params: { kind: 'trait-impl', path: 'x::y' } });
    const { outcomes } = renderCargoClippy([n]);
    const outcome = outcomes.get('r4');
    expect(outcome?.kind).toBe('refused');
    expect((outcome as Extract<RenderOutcome, { kind: 'refused' }>).code).toBe('FF7002');
  });

  it('R5: defaultSeverity "error" -> degraded FF7003 AND toml still contains the entry', () => {
    const n = node({ id: 'r5', defaultSeverity: 'error' });
    const { toml, outcomes } = renderCargoClippy([n]);
    const outcome = outcomes.get('r5');
    expect(outcome?.kind).toBe('degraded');
    expect((outcome as Extract<RenderOutcome, { kind: 'degraded' }>).code).toBe('FF7003');
    expect(toml).toContain('std::env::var');
  });

  it('R5b: defaultSeverity "note" -> degraded FF7003, entry still emitted (regression guard: note must not desert the error/note else-branch)', () => {
    // R5 only exercises 'error'. 'note' shares the same else-branch today; this guards a
    // future regression where someone splits that branch and mis-routes 'note' away from
    // degraded/FF7003. The FF7003 diag carries requested === 'note' (the severity that
    // could not be projected), and the entry is STILL emitted (degraded = rendered-with-loss).
    const n = node({ id: 'r5b', defaultSeverity: 'note' });
    const { toml, outcomes } = renderCargoClippy([n]);
    const outcome = outcomes.get('r5b');
    expect(outcome?.kind).toBe('degraded');
    expect((outcome as Extract<RenderOutcome, { kind: 'degraded' }>).code).toBe('FF7003');
    expect((outcome as Extract<RenderOutcome, { kind: 'degraded' }>).note).toContain('severity');
    expect(toml).toContain('std::env::var');
  });

  it('P5: FIXTURE_NODE (warning severity) -> rendered, toml byte-for-byte == golden', () => {
    const { toml, outcomes } = renderCargoClippy([FIXTURE_NODE]);
    const outcome = outcomes.get('no-direct-env-var');
    expect(outcome?.kind).toBe('rendered');
    const golden =
      '# generated by getff cargo backend v0 — do not edit by hand\n' +
      'disallowed-methods = [\n' +
      '    { path = "std::env::var", reason = "Read configuration through the injected config accessor, never std::env::var directly" },\n' +
      ']\n';
    expect(toml).toBe(golden);
  });

  it('R6: outcomes missing a node -> assertEveryNodeResolved throws', () => {
    const outcomes = new Map<string, RenderOutcome>();
    expect(() => assertEveryNodeResolved(['missing-1'], outcomes)).toThrow();
  });

  it('R6b: outcomes carrying an unexpected/extra node -> assertEveryNodeResolved throws (second path: size mismatch)', () => {
    // Every expected nodeId IS present (so the first "missing" throw does NOT fire),
    // but the map carries an additional entry not in nodeIds -> size 2 !== length 1
    // triggers the SECOND throw (outcomes.size !== nodeIds.length), the branch R6 misses.
    const outcomes = new Map<string, RenderOutcome>([
      ['a', { kind: 'rendered', surfaces: [{ surface: 'rule', content: 'disallowed-methods' }] }],
      ['b', { kind: 'rendered', surfaces: [{ surface: 'rule', content: 'disallowed-methods' }] }],
    ]);
    expect(() => assertEveryNodeResolved(['a'], outcomes)).toThrow();
  });
});

describe('renderCargoClippy — TOML shape (disallowed-types / disallowed-macros)', () => {
  it('kind "type" routes into disallowed-types table', () => {
    const n = node({
      id: 'no-raw-vec',
      params: { kind: 'type', path: 'std::vec::Vec' },
      claim: 'Use the bounded collection wrapper instead of raw Vec',
    });
    const { toml } = renderCargoClippy([n]);
    expect(toml).toContain('disallowed-types');
    expect(toml).toContain('std::vec::Vec');
  });

  it('kind "macro" routes into disallowed-macros table', () => {
    const n = node({
      id: 'no-dbg',
      params: { kind: 'macro', path: 'std::dbg' },
      claim: 'Remove dbg! before committing',
    });
    const { toml } = renderCargoClippy([n]);
    expect(toml).toContain('disallowed-macros');
    expect(toml).toContain('std::dbg');
  });

  it('replacement param, when present, is emitted', () => {
    const n = node({
      id: 'with-replacement',
      params: { kind: 'method', path: 'std::env::var', replacement: 'app_config::env_var' },
    });
    const { toml } = renderCargoClippy([n]);
    expect(toml).toContain('replacement = "app_config::env_var"');
  });

  it('entries are sorted by nodeId for determinism', () => {
    const nb = node({ id: 'zzz-last', params: { kind: 'method', path: 'std::env::var' } });
    const na = node({ id: 'aaa-first', params: { kind: 'method', path: 'std::process::exit' } });
    const { toml } = renderCargoClippy([nb, na]);
    const idxFirst = toml.indexOf('std::process::exit');
    const idxLast = toml.indexOf('std::env::var');
    expect(idxFirst).toBeGreaterThan(-1);
    expect(idxLast).toBeGreaterThan(-1);
    expect(idxFirst).toBeLessThan(idxLast);
  });

  it('double quotes in reason are escaped', () => {
    const n = node({
      id: 'quoted-reason',
      claim: 'Use "the accessor" not env::var',
      params: { kind: 'method', path: 'std::env::var' },
    });
    const { toml } = renderCargoClippy([n]);
    expect(toml).toContain('reason = "Use \\"the accessor\\" not env::var"');
  });
});
