#!/usr/bin/env bash
# check-shields-up.sh — prove installed Husky shields are wired and active.
#
# Asserts:
#   1. git core.hooksPath RESOLVES to an existing husky hooks dir — '<root>/.husky' (husky v8)
#      or '<root>/.husky/_' (husky v9). Resolution, not string equality: see the block at
#      "Check 1" below for the measurement that forced this.
#   2. .husky/pre-commit exists, is executable, and references 'lint-staged' (the gate command)
#   3. .husky/pre-push exists, is executable, and references the pre-push dispatcher
#
# Behavioural smoke (invoke hook against a bad fixture in a scratch sandbox) is deferred
# as a fast-follow: the gate-wiring check above catches the most common failure mode
# (shields raised but not wired; hooksPath overridden by a subsequent git config call).
#
# SKIP GRACEFULLY when not inside a git repo (e.g. container with no .git) — rc=0.
#
# CONSUMER PATH: scripts/check-shields-up.sh (copied by setup.d/40-configs.sh).
#
# @cc-only-rationale: sourced by install.sh dispatcher and consumer scripts; pure bash,
#   no CC primitives.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Resolve project root ──────────────────────────────────────────────────────
if [ -n "${AIF_PROJECT_ROOT:-}" ]; then
  PROJECT_ROOT="$AIF_PROJECT_ROOT"
elif command -v git &>/dev/null && git -C "$SCRIPT_DIR" rev-parse --show-toplevel &>/dev/null 2>&1; then
  PROJECT_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
elif [ -d "$SCRIPT_DIR/../scripts" ] && [ -d "$SCRIPT_DIR/../node_modules" ]; then
  # Consumer: script lives at PROJECT_ROOT/scripts/check-shields-up.sh
  PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
elif [ -d "$SCRIPT_DIR/../../../packages" ]; then
  # Framework: script lives at packages/core/audit-self/check-shields-up.sh
  PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
else
  PROJECT_ROOT="$(pwd)"
fi

PASS=0; FAIL=0; SKIP=0
ok()   { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad()  { FAIL=$((FAIL+1)); echo "  ✗ $1"; }
skip() { SKIP=$((SKIP+1)); echo "  · $1"; }

# ─── Must be inside a git repo ───────────────────────────────────────────────
if ! command -v git &>/dev/null; then
  skip "check-shields-up SKIP — git not available"
  echo ""; echo "PASS=$PASS FAIL=$FAIL SKIP=$SKIP"; exit 0
fi

if ! git -C "$PROJECT_ROOT" rev-parse --show-toplevel &>/dev/null 2>&1; then
  skip "check-shields-up SKIP — $PROJECT_ROOT is not a git repository (Husky requires git)"
  echo ""; echo "PASS=$PASS FAIL=$FAIL SKIP=$SKIP"; exit 0
fi

GIT_ROOT="$(git -C "$PROJECT_ROOT" rev-parse --show-toplevel)"

echo "▶ check-shields-up: git root $GIT_ROOT"

# ─── Check 1: core.hooksPath resolves to an EXISTING husky hooks dir ──────────
#
# WHY resolution and not `[ "$HOOKS_PATH" = ".husky/_" ]` (measured 2026-08-17 in a consumer
# repo — timeliner, a ~41-worktree clone — where the literal compare was a permanent source of
# a red `pnpm validate` on clean trunk):
#
#   * git accepts core.hooksPath in TWO forms and honours both. Relative values resolve
#     against the TOP-LEVEL OF THE WORKING TREE (not the cwd — verified by firing a marker
#     hook with git invoked from a subdirectory). Absolute values are used as-is.
#     The old literal compare called the absolute form "shields not pointing to the
#     installed hooks" while the hooks were demonstrably firing.
#
#   * On a multi-worktree clone the absolute form is the SAFER one, and that is not a
#     preference: core.hooksPath is repo-local config SHARED by every worktree, but `.husky/_`
#     (the wrapper dir) is generated by husky's `prepare` and gitignored, so it exists only in
#     checkouts where the package install was actually run. Measured on that clone: 18 of 41
#     registered worktrees have no `.husky/_`. With the relative value those 18 fire NO hooks
#     at all, silently. With the absolute value every worktree runs the main clone's wrappers.
#     A "fix" that rewrites the config to the relative form to satisfy a string compare
#     therefore greens the gate by DISARMING the shields — strictly worse.
#
#   * The config value is not stably ownable by hand either way: husky v9's index.js runs
#     `git config core.hooksPath <dir>/_` UNCONDITIONALLY on every `prepare`, i.e. on every
#     install (verified against husky 9.1.7 in a scratch repo: an absolute value was
#     overwritten with `.husky/_`). So the ONLY durable place to encode "both forms are
#     valid" is this gate.
#
# The existence check below is not decoration: it closes a false-GREEN the literal compare
# had. A bare `.husky/_` string passed even in a checkout where that directory does not
# exist — gate green, every shield silently dead. Now such a checkout reads RED, truthfully.
#
# Deferred (same fast-follow as the behavioural smoke): asserting the per-hook WRAPPERS
# (<resolved>/pre-commit, <resolved>/pre-push) exist, not just the directory.
HOOKS_PATH="$(git -C "$GIT_ROOT" config core.hooksPath 2>/dev/null || true)"
if [ -z "$HOOKS_PATH" ]; then
  bad "core.hooksPath not set — Husky hooks are NOT wired (run ./setup or git config core.hooksPath .husky)"
else
  case "$HOOKS_PATH" in
    /*) RESOLVED_HOOKS="$HOOKS_PATH" ;;
    *)  RESOLVED_HOOKS="$GIT_ROOT/$HOOKS_PATH" ;;
  esac
  RESOLVED_HOOKS="${RESOLVED_HOOKS%/}"
  # husky v9 points at <root>/.husky/_ (wrapper dir), husky v8 at <root>/.husky
  HOOKS_BASE="${RESOLVED_HOOKS%/_}"
  if [ "${HOOKS_BASE##*/}" != ".husky" ]; then
    bad "core.hooksPath = '$HOOKS_PATH' → '$RESOLVED_HOOKS' is not a husky hooks dir (expected <root>/.husky or <root>/.husky/_) — shields not pointing to the installed hooks"
  elif [ ! -d "$RESOLVED_HOOKS" ]; then
    bad "core.hooksPath = '$HOOKS_PATH' → '$RESOLVED_HOOKS' does not exist — git finds no hook there and skips every shield SILENTLY (re-run the package install in this checkout to regenerate the husky wrappers, or point core.hooksPath at a checkout that has them)"
  else
    ok "core.hooksPath = '$HOOKS_PATH' → $RESOLVED_HOOKS exists — hooks are wired (.husky = husky v8, .husky/_ = husky v9; absolute and relative are both valid, see the block above)"
  fi
fi

HUSKY_DIR="$GIT_ROOT/.husky"

# ─── Check 2: .husky/pre-commit ───────────────────────────────────────────────
PRE_COMMIT="$HUSKY_DIR/pre-commit"
if [ ! -f "$PRE_COMMIT" ]; then
  bad "pre-commit hook missing at $PRE_COMMIT — commit-time shield not installed"
elif [ ! -x "$PRE_COMMIT" ]; then
  bad "$PRE_COMMIT exists but is not executable — chmod +x .husky/pre-commit to activate"
elif grep -q '@aif-shield' "$PRE_COMMIT" 2>/dev/null; then
  ok "pre-commit: present, executable, carries the @aif-shield marker — framework commit shield WIRED (form check: framework-owned hook present; behavioural commit probe is a planned gate)"
elif grep -q 'lint-staged' "$PRE_COMMIT" 2>/dev/null; then
  bad "pre-commit: runs lint-staged but LACKS the @aif-shield marker — a competing git-hooks manager (e.g. simple-git-hooks via a 'prepare' script) has replaced the framework hook; the sibling pre-push was likely clobbered too. Re-run install (re-asserts .husky/*) or restore .husky/pre-commit. (GH #975)"
else
  bad "pre-commit: present + executable but is not the framework shield (no @aif-shield marker, no lint-staged) — shield content unexpected (check $PRE_COMMIT)"
fi

# ─── Check 3: .husky/pre-push ─────────────────────────────────────────────────
PRE_PUSH="$HUSKY_DIR/pre-push"
if [ ! -f "$PRE_PUSH" ]; then
  bad "pre-push hook missing at $PRE_PUSH — push-time shield not installed"
elif [ ! -x "$PRE_PUSH" ]; then
  bad "$PRE_PUSH exists but is not executable — chmod +x .husky/pre-push to activate"
else
  # The shipped pre-push must reference the TS-core dispatcher (pre-push.ts) or the fallback
  if grep -qE '(pre-push\.ts|pre-push\.fallback\.sh)' "$PRE_PUSH" 2>/dev/null; then
    ok "pre-push: present, executable, references pre-push dispatcher — push shield WIRED (form check: hook present + references dispatcher; behavioural push probe is a planned gate)"
  else
    bad "pre-push: present + executable but does not reference pre-push.ts or pre-push.fallback.sh — shield may be empty stub (check $PRE_PUSH)"
  fi
fi

echo ""
echo "PASS=$PASS FAIL=$FAIL SKIP=$SKIP"
[ "$FAIL" -eq 0 ]
