// Curated Python starter node set — unit tests (python-delivery-v0 umbrella, S1 Task 3).
// Spec/prior-art: docs/meta-factory/prior-art-evaluations.md#217 (curated Python starter set as
// own content in the neutral IR, rendered through the ADOPTED #212 ast-grep + #215 ruff backends).
//
// RED-first (superpowers:test-driven-development): authored BEFORE starter-nodes.ts — run to confirm
// it fails to import the module, then implement until every case below is GREEN.
//
// The set is validated against the FROZEN artefacts only (ir/types.ts, ir/gates/grammar.ts,
// backends/{astgrep,ruff}/render-*.ts) — this task adds NO IR field and does NOT touch a render module.

import { describe, expect, it } from 'vitest';
import { runGrammarGate } from '../ir/gates/grammar.ts';
import { renderAstgrep } from '../backends/astgrep/render-astgrep.ts';
import { renderRuff } from '../backends/ruff/render-ruff.ts';
import type { RenderOutcome } from '../backends/shared/render-outcome.ts';
import { PYTHON_STARTER_NODES } from './starter-nodes.ts';

function refused(o: RenderOutcome | undefined): Extract<RenderOutcome, { kind: 'refused' }> {
  return o as Extract<RenderOutcome, { kind: 'refused' }>;
}

describe('PYTHON_STARTER_NODES — set is well-formed', () => {
  it('is a non-empty ConventionNode[]', () => {
    expect(Array.isArray(PYTHON_STARTER_NODES)).toBe(true);
    expect(PYTHON_STARTER_NODES.length).toBeGreaterThan(0);
  });

  it('passes the IR grammar gate (shape + no dup id + non-degenerate pairs + no dangling anchor)', () => {
    expect(runGrammarGate(PYTHON_STARTER_NODES).status).toBe('pass');
  });

  it('every rule id is namespaced `getff-*` (probe-proven: un-namespaced ids collide with consumer rules -> ast-grep exit 8)', () => {
    for (const n of PYTHON_STARTER_NODES) {
      expect(n.id.startsWith('getff-'), `id must be getff-namespaced: ${n.id}`).toBe(true);
    }
  });

  it('rule ids are unique', () => {
    const ids = PYTHON_STARTER_NODES.map((n) => n.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe('PYTHON_STARTER_NODES — routes to the astgrep backend (#212)', () => {
  it('renders through renderAstgrep without error; every node resolves; >=1 rendered', () => {
    const { yaml, outcomes } = renderAstgrep(PYTHON_STARTER_NODES);
    expect(outcomes.size).toBe(PYTHON_STARTER_NODES.length);
    const rendered = [...outcomes.values()].filter((o) => o.kind === 'rendered');
    expect(rendered.length).toBeGreaterThan(0);
    expect(yaml).toContain('# generated by getff astgrep backend v0');
  });

  it('the flagship no-datetime-now ban is rendered (P5)', () => {
    const { outcomes } = renderAstgrep(PYTHON_STARTER_NODES);
    expect(outcomes.get('getff-no-datetime-now')?.kind).toBe('rendered');
  });

  it('DATETIME CAVEAT: the rendered rule content covers BOTH datetime.now() and datetime.datetime.now()', () => {
    // Probe-proven (Task 2 §c + this task's live re-probe): `pattern: datetime.now()` does NOT match
    // `datetime.datetime.now()`. The frozen renderer emits a single `pattern:` per rule (no `any:`
    // block), so both forms are covered by two literal-pattern nodes -> the rendered YAML must carry
    // BOTH patterns. A single-form ban (regression) fails this test.
    //
    // S3 narrow (getff-honest-signals §8.3): patterns are zero-arg only — `$$$ARGS` was removed
    // because it caught the ruff-recommended `datetime.now(timezone.utc)` form. See S3 §1.
    const { yaml } = renderAstgrep(PYTHON_STARTER_NODES);
    expect(yaml).toContain('pattern: "datetime.now()"');
    expect(yaml).toContain('pattern: "datetime.datetime.now()"');
  });

  it('the rendered datetime rules match the probe-proven firing shape (id/language/severity/metadata/rule)', () => {
    const { yaml } = renderAstgrep(PYTHON_STARTER_NODES);
    expect(yaml).toContain('id: "getff-no-datetime-datetime-now"');
    expect(yaml).toContain('language: python');
    expect(yaml).toContain('severity: error');
    expect(yaml).toContain('  kind: call');
  });
});

describe('PYTHON_STARTER_NODES — routes to the ruff backend (#215 fast-path)', () => {
  it('renders through renderRuff without error; every node resolves; >=1 rendered', () => {
    const { toml, outcomes } = renderRuff(PYTHON_STARTER_NODES);
    expect(outcomes.size).toBe(PYTHON_STARTER_NODES.length);
    const rendered = [...outcomes.values()].filter((o) => o.kind === 'rendered');
    expect(rendered.length).toBeGreaterThan(0);
    expect(toml).toContain('# generated by getff ruff backend v0');
  });

  it('emits TID251 banned-api (the utcnow qualified-name ban) with the node claim as its message', () => {
    const { toml, outcomes } = renderRuff(PYTHON_STARTER_NODES);
    expect(outcomes.get('getff-no-utcnow')?.kind).toBe('rendered');
    expect(toml).toContain('TID251');
    expect(toml).toContain('"datetime.datetime.utcnow".msg =');
  });

  it('emits TID253 banned-module-level-imports (the tensorflow module ban)', () => {
    const { toml, outcomes } = renderRuff(PYTHON_STARTER_NODES);
    expect(outcomes.get('getff-no-tensorflow-module-import')?.kind).toBe('rendered');
    expect(toml).toContain('TID253');
    expect(toml).toContain('banned-module-level-imports = ["tensorflow"]');
  });

  it('the call-with-args bans (datetime.now/eval/os.system) refuse FF7001 on ruff — the fast-path boundary (astgrep is the catch-all)', () => {
    const { outcomes } = renderRuff(PYTHON_STARTER_NODES);
    for (const id of ['getff-no-datetime-now', 'getff-no-datetime-datetime-now', 'getff-no-eval', 'getff-no-os-system']) {
      expect(outcomes.get(id)?.kind, `${id} should refuse on ruff`).toBe('refused');
      expect(refused(outcomes.get(id)).code, `${id} refusal code`).toBe('FF7001');
    }
  });
});
