#!/usr/bin/env bash
# render-terms-style.test.sh — acceptance arms for scripts/render-terms-style.mjs (getff-ai-site S0q).
#
# Live-fire, never a source grep: every arm RUNS the real renderer (plain node — the script is
# ESM with no repo imports) against either the real repo (idempotence + check arms) or a
# throwaway mktemp fixture root, and asserts output + exit codes. Arms:
#   1. --check on the real repo: exit 0 — the committed Names.yml matches terms.md region (a).
#   2. --write on the real repo is idempotent: byte-identical file, exit 0.
#   3. a fixture entry renders the swap: literal keys quoted, the acronym-like form
#      word-bounded (D-Q7 «CC (word-bounded)», measured on Vale 3.21.0).
#   4. paired negative: a tampered Names.yml fails --check naming the drift; --write heals it.
#   5. a missing Names.yml fails --check naming the file.
#   6. region isolation: a stray `Do not use (name):` line after the next `## ` heading is
#      NOT absorbed (D-Q7: only region (a) entries render).
#   7. Vale live-fire (skipped LOUDLY when no binary): the rendered rule actually fires as an
#      error on the forbidden form and stays silent on the canonical one.
#
# Pure bash + plain node; no network, no LLM (no-paid-llm-in-ci.md).
set -u
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)
cd "$REPO_ROOT" || exit 1

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad() { FAIL=$((FAIL+1)); echo "  ✗ $1"; }
GEN="scripts/render-terms-style.mjs"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# ── Arm 1: --check on the real repo ───────────────────────────────────────────────────────────
out=$(node "$GEN" --check 2>&1); rc=$?
if [ $rc -eq 0 ] && echo "$out" | grep -q 'matches docs/site/terms.md region (a)'; then
  ok "arm 1: --check exits 0 on the real repo (committed Names.yml matches terms.md)"
else
  bad "arm 1: --check rc=$rc (out: $(echo "$out" | head -2 | tr '\n' ' '))"
fi

# ── Arm 2: --write is idempotent ──────────────────────────────────────────────────────────────
NAMES=docs/site-quality/vale/styles/getff/Names.yml
before=$(sha256sum "$NAMES" | cut -d' ' -f1)
node "$GEN" --write >/dev/null 2>&1
after=$(sha256sum "$NAMES" | cut -d' ' -f1)
if [ "$before" = "$after" ]; then
  ok "arm 2: --write is idempotent (byte-identical Names.yml)"
else
  bad "arm 2: --write changed the committed Names.yml ($before -> $after)"
fi

# ── fixture helper: a minimal region (a) ──────────────────────────────────────────────────────
make_fixture() {
  local root="$1"
  mkdir -p "$root/docs/site" "$root/docs/site-quality/vale/styles/getff"
  cat >"$root/docs/site/terms.md" <<'MD'
---
title: Terms
description: Fixture glossary.
kind: glossary
sources:
  - example.md
---

## Terms

<!-- vale off -->
<!-- vale-reason: fixture block naming forbidden forms; the escape keeps the profile quiet -->

### widget

A thing the fixture defines.

Do not use (name): gizmo, CC — the old names; retired before the site shipped.

<!-- vale on -->

## Artifact names

<!-- getff:begin section=artifact-names plan=scripts/render-reference.mjs -->
<!-- generated region -->
<!-- getff:end section=artifact-names -->
MD
}

# ── Arm 3: the fixture renders the swap (quoted literals + word-bounded acronym) ──────────────
make_fixture "$TMP/render"
out=$(node "$GEN" --write --root "$TMP/render" 2>&1); rc=$?
if [ $rc -eq 0 ] && echo "$out" | grep -q 'wrote docs/site-quality/vale/styles/getff/Names.yml'; then
  ok "arm 3: --write exits 0 on the fixture"
else
  bad "arm 3: --write rc=$rc (out: $out)"
fi
genswap=$(grep -c '"gizmo"' "$TMP/render/$NAMES" || true)
ccswap=$(grep -c '"(?<!\[A-Za-z0-9-\])CC(?!\[A-Za-z0-9-\])"' "$TMP/render/$NAMES" || true)
mapped=$(grep -c '"gizmo": "widget"' "$TMP/render/$NAMES" || true)
ccmapped=$(grep -A0 'CC(?!\[A-Za-z0-9-\])": "widget"' "$TMP/render/$NAMES" | grep -c 'widget' || true)
if [ "$genswap" -ge 1 ] && [ "$mapped" -ge 1 ]; then
  ok "arm 3: the literal forbidden form renders as a quoted swap to the canonical term"
else
  bad "arm 3: the gizmo->widget swap did not render (grep counts: $genswap/$mapped)"
fi
if [ "$ccswap" -ge 1 ] && [ "$ccmapped" -ge 1 ]; then
  ok "arm 3: the acronym-like form renders word-bounded (D-Q7 CC measured form)"
else
  bad "arm 3: the CC form lost its word-boundary lookarounds (count: $ccswap/$ccmapped)"
fi

# ── Arm 4: paired negative — tampered Names.yml fails --check; --write heals ──────────────────
make_fixture "$TMP/drift"
node "$GEN" --write --root "$TMP/drift" >/dev/null 2>&1
printf '# GENERATED by scripts/render-terms-style.mjs — do not hand-edit.\n# Source: docs/site/terms.md region (a) — the `Do not use (name):` entries (D-Q7).\n# Regenerate: node scripts/render-terms-style.mjs --write\nextends: substitution\nmessage: Use '"'"'%%s'"'"' instead of '"'"'%%s'"'"'.\nlevel: error\nignorecase: false\nswap:\n  "tampered": "widget"\n' >"$TMP/drift/$NAMES"
out=$(node "$GEN" --check --root "$TMP/drift" 2>&1); rc=$?
if [ $rc -ne 0 ] && echo "$out" | grep -q 'drifted from docs/site/terms.md region (a)'; then
  ok "arm 4: a tampered Names.yml fails --check naming the drift"
else
  bad "arm 4: --check rc=$rc on a tampered Names.yml (out: $(echo "$out" | head -2 | tr '\n' ' '))"
fi
node "$GEN" --write --root "$TMP/drift" >/dev/null 2>&1
node "$GEN" --check --root "$TMP/drift" >/dev/null 2>&1; rc=$?
if [ $rc -eq 0 ]; then
  ok "arm 4: --write heals the drift; --check then exits 0"
else
  bad "arm 4: --check still failing after --write (rc=$rc)"
fi

# ── Arm 5: missing Names.yml fails --check ────────────────────────────────────────────────────
make_fixture "$TMP/missing"
out=$(node "$GEN" --check --root "$TMP/missing" 2>&1); rc=$?
if [ $rc -ne 0 ] && echo "$out" | grep -q 'Names.yml is missing'; then
  ok "arm 5: a missing Names.yml fails --check naming the artefact"
else
  bad "arm 5: --check rc=$rc on a missing Names.yml (out: $(echo "$out" | head -2 | tr '\n' ' '))"
fi

# ── Arm 6: region isolation — a stray entry line after `## ` is not absorbed ──────────────────
make_fixture "$TMP/isolate"
cat >>"$TMP/isolate/docs/site/terms.md" <<'MD'

Do not use (name): strayswap — this line sits below the region (a) boundary.
MD
node "$GEN" --write --root "$TMP/isolate" >/dev/null 2>&1
if grep -q 'strayswap' "$TMP/isolate/$NAMES"; then
  bad "arm 6: a stray Do-not-use line outside region (a) leaked into the swap map"
else
  ok "arm 6: the stray line after the next ## heading is ignored (region boundary holds)"
fi

# ── Arm 7: Vale live-fire (skipped LOUDLY when the binary is absent) ──────────────────────────
VALE_BIN="${VALE_BIN:-$(command -v vale || true)}"
if [ -z "$VALE_BIN" ]; then
  echo "  ⚠ arm 7 SKIPPED: no vale binary on PATH (set VALE_BIN to run it locally);"
  echo "    the audit-self.yml docs-check job live-fires this profile in CI."
else
  make_fixture "$TMP/vale"
  cp -r "$REPO_ROOT/docs/site-quality/vale/.vale.ini" "$TMP/vale/docs/site-quality/vale/"
  cp -r "$REPO_ROOT/docs/site-quality/vale/styles" "$TMP/vale/docs/site-quality/vale/"
  node "$GEN" --write --root "$TMP/vale" >/dev/null 2>&1
  cat >"$TMP/vale/docs/site/bad.md" <<'MD'
---
title: Bad
description: Fixture page.
kind: glossary
sources:
  - example.md
---

# Bad

The gizmo ships today.
MD
  cat >"$TMP/vale/docs/site/good.md" <<'MD'
---
title: Good
description: Fixture page.
kind: glossary
sources:
  - example.md
---

# Good

The widget ships today.
MD
  out=$("$VALE_BIN" --config="$TMP/vale/docs/site-quality/vale/.vale.ini" --output=line \
    "$TMP/vale/docs/site/bad.md" "$TMP/vale/docs/site/good.md" 2>&1); rc=$?
  if [ $rc -ne 0 ] && echo "$out" | grep -q 'getff.Names:Use '"'"'widget'"'"' instead of '"'"'gizmo'"'"'' \
    && ! echo "$out" | grep -q 'good.md.*getff.Names'; then
    ok "arm 7: the rendered rule fires as an error on the forbidden form, silent on the canonical one"
  else
    bad "arm 7: unexpected vale result rc=$rc (out: $(echo "$out" | head -4 | tr '\n' ' '))"
  fi
fi

echo "render-terms-style.test.sh: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
