#!/usr/bin/env bash
# setup.d/47-go.sh — Go toolchain delivery layer (adapter-jig J3).
#
# Ships the pre-rendered golangci-lint bundle (.golangci.yml authored at
# packages/core/templates/go/.golangci.yml) into a consumer Go module with an AUGMENT-FIRST
# collision policy: never silently clobber a config the consumer already authored. This is the
# go analog of the cargo lane (setup.d/46-cargo.sh); it delivers the golangci-lint ban surface
# + the go rules-lock variant (kickoff §1 W4 → J3). No new delivery channel — it rides the same
# install.sh env-var contract the Python/cargo lanes established.
#
# COLLISION MATRIX (mirrors the 46-cargo cells, adapted to go's single-file layout):
#   (i)   fresh dir (no .golangci.yml)      → copy whole template file.
#   (ii)  pre-existing .golangci.yml         → REFUSE-LOUDLY. A sibling .golangci.yml of ours
#         (consumer-authored, no getff hdr)  would REPLACE theirs entirely (golangci-lint reads
#                                           exactly one .golangci.yml at the repo root). Ship our
#                                           rules as getff-golangci.yml (golangci-lint does NOT
#                                           auto-discover it — inert until they opt in) + print
#                                           merge instructions.
#   (rules-lock) reproducibility record      → ALWAYS write .ai-factory/synthesizer-output/rules-lock.go.json
#                                           (emittedAt + sourceFingerprint of the DELIVERED
#                                           golangci config — getff-golangci.yml in the REFUSE
#                                           cell, never the consumer's own file).
#   (ci)  consumer CI workflow               → ship the pinned golangci-lint gate as a
#                                           getff-NAMESPACED .github/workflows/getff-go.yml
#                                           (never the consumer's ci.yml).
#                                           Fresh | idempotent-if-ours | REFUSE-LOUDLY if a
#                                           non-getff file occupies our path.
#   (v)   re-run                             → zero diff on the delivered CONFIG artefacts (idempotent).
#
# INERT-ON-NPM CONTRACT (critical): install.sh sources ALL setup.d/[0-9]*.sh unconditionally, so
# this layer MUST no-op on the default npm flow. It runs ONLY when the go lane is explicitly
# activated via the env-var contract GETFF_TOOLCHAIN=go (install.sh do_go_lane sets it); until
# then nothing sets it, so every npm `./setup`/`install.sh` sources this file to a pure no-op
# (byte-identical.test.sh stays green — the npm baselines never see a go artefact).
#
# @cc-only-rationale: sourced by the install.sh dispatcher into its shell scope (not exec'd), so
#   it reuses lib.sh helpers (copy_safe/refresh_safe) already in scope — no standalone entrypoint.
#   The augment/refuse transforms below are go-lane-specific, so they live here; no lib.sh helper
#   body is copy-pasted (layer-units.test.sh §4 SSOT guard).
#
# Delivery-log: every action + degrade path is printed to stdout AND appended to
#   <consumer>/.getff-go-install.log (a running audit trail; NOT a delivered config artefact, so
#   it is excluded from the (v) idempotency checksum + the snapshot fingerprint — the configs are
#   byte-stable).

# ── go-lane delivery helpers (defined always; executed only under the activation guard) ──

# Delivery-log sink: print to stdout (install progress) AND append to the consumer audit log.
_go_log() {
  echo "  $1"
  if [ "${DRY_RUN:-}" != "--dry-run" ] && [ -n "${_GO_LOG_FILE:-}" ]; then
    printf '%s\n' "$1" >> "$_GO_LOG_FILE"
  fi
}

# _go_copy_or_refresh <src> <dst> — FRAMEWORK-OWNED delivery. On install: copy_safe (skip-if-exists
# → idempotent re-run). On --refresh (do_go_lane sets GETFF_TOOLCHAIN_REFRESH=1): refresh_safe →
# OVERWRITE, so updated framework content reaches a brownfield consumer; refresh_safe honours a
# sibling <dst>.override.md (Layer-3 consumer ownership). Mirrors _cargo_copy_or_refresh.
_go_copy_or_refresh() {
  if [ "${GETFF_TOOLCHAIN_REFRESH:-}" = "1" ]; then
    refresh_safe "$1" "$2"
  else
    copy_safe "$1" "$2"
  fi
}

# _go_delivered_golangci_path — resolve which golangci-lint config THIS lane delivered for the
# active cell: getff-owned .golangci.yml (greenfield / idempotent — getff header present) →
# .golangci.yml; REFUSE cell (consumer-authored .golangci.yml kept, ours shipped inert) →
# getff-golangci.yml. Invariant (adapter-jig E2, the W4 cargo finding-1 class): the firing
# self-check proves the DELIVERED rules fire and the rules-lock fingerprints the DELIVERED
# artefact — never the consumer's own config (it lacks our bans and is not ours to attest).
_go_delivered_golangci_path() {
  if [ -e "$PROJECT_ROOT/.golangci.yml" ] && grep -q 'generated by getff' "$PROJECT_ROOT/.golangci.yml" 2>/dev/null; then
    printf '%s' "$PROJECT_ROOT/.golangci.yml"
  elif [ -e "$PROJECT_ROOT/getff-golangci.yml" ]; then
    printf '%s' "$PROJECT_ROOT/getff-golangci.yml"
  else
    # Pre-delivery / seam invocation with no getff artefact yet: best effort — every caller
    # re-checks existence before use, so a missing path degrades loudly there, never silently.
    printf '%s' "$PROJECT_ROOT/.golangci.yml"
  fi
}

# _go_deliver_golangci — .golangci.yml lane: fresh copy | idempotent-if-getff | REFUSE (consumer's own).
_go_deliver_golangci() {
  local tpl="$1"
  local dst="$PROJECT_ROOT/.golangci.yml"
  local getff_ref="$PROJECT_ROOT/getff-golangci.yml"

  # Idempotency: a .golangci.yml WE already delivered (getff header) is not a consumer collision.
  if [ -e "$dst" ] && grep -q 'generated by getff' "$dst" 2>/dev/null; then
    if [ "${GETFF_TOOLCHAIN_REFRESH:-}" = "1" ]; then
      refresh_safe "$tpl/.golangci.yml" "$dst"
      _go_log ".golangci.yml → refreshed (framework-owned getff copy)"
    else
      _go_log "⊝ .golangci.yml already delivered by getff — no-op (idempotent)"
    fi
  elif [ -e "$dst" ]; then
    # (ii) consumer-authored .golangci.yml → a sibling of ours would REPLACE it (golangci-lint
    # reads ONE .golangci.yml). REFUSE: ship getff-golangci.yml (golangci-lint does not
    # auto-discover it) + merge note.
    _go_copy_or_refresh "$tpl/.golangci.yml" "$getff_ref"
    _go_log "⚠ REFUSE .golangci.yml (cell ii): a sibling .golangci.yml would REPLACE your existing one entirely."
    _go_log "  Shipped our rules as getff-golangci.yml (golangci-lint does NOT auto-discover it — inert until you opt in)."
    _go_log "  MANUAL: merge the getff forbidigo entries from getff-golangci.yml into your .golangci.yml, OR run:"
    _go_log "    golangci-lint run --enable forbidigo --config getff-golangci.yml ./..."
  else
    # (i) fresh: no .golangci.yml → copy ours whole.
    copy_safe "$tpl/.golangci.yml" "$dst"
    _go_log ".golangci.yml → copied (fresh dir, cell i)"
  fi
}

# _go_deliver_ci — .github/workflows/getff-go.yml lane: fresh copy | idempotent-if-getff |
# REFUSE-LOUDLY (consumer's own). NEVER writes to the consumer's ci.yml — a pre-existing
# consumer CI workflow is not clobbered. Parity with _cargo_deliver_ci.
_go_deliver_ci() {
  local tpl="$1"
  local wf_dst="$PROJECT_ROOT/.github/workflows/getff-go.yml"

  if [ ! -f "$tpl/github-actions-ci.yml" ]; then
    _go_log "⊝ no CI template at $tpl/github-actions-ci.yml — skipping CI delivery (rules still enforced locally)"
    return 0
  fi

  if [ -e "$wf_dst" ]; then
    if grep -q 'generated by getff' "$wf_dst" 2>/dev/null; then
      if [ "${GETFF_TOOLCHAIN_REFRESH:-}" = "1" ]; then
        # Framework-owned → refresh_safe overwrites so updated pins reach a brownfield consumer.
        refresh_safe "$tpl/github-actions-ci.yml" "$wf_dst"
        _go_log "CI workflow → refreshed (.github/workflows/getff-go.yml, framework-owned pins)"
      else
        _go_log "⊝ .github/workflows/getff-go.yml already delivered by getff — no-op (idempotent)"
      fi
      return 0
    fi
    # A NON-getff file occupies our namespaced path → a consumer authored it. REFUSE, never clobber.
    # NOTE: the pins below intentionally MIRROR github-actions-ci.yml (the delivered template) —
    # a printed manual-wiring hint cannot --config-dedupe against a YAML file without a parser
    # we do not assume in pure bash; the CI-template pins are the SSOT and these strings restate
    # them for the refuse path. Keep the two in sync on any pin bump (both bump together per
    # ci-tool-pinning.md Rule A + F10 two-surface pin parity).
    _go_log "⚠ REFUSE CI: .github/workflows/getff-go.yml exists and is NOT getff-generated."
    _go_log "  NOT overwriting your workflow. To wire the getff Go gates, add a job running:"
    _go_log "      go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2"
    _go_log "      golangci-lint run --enable forbidigo --config .golangci.yml ./...    # your config"
    return 0
  fi

  # Fresh: copy the pinned CI workflow whole (framework-owned, getff-header-marked, getff-namespaced).
  copy_safe "$tpl/github-actions-ci.yml" "$wf_dst"
  _go_log "CI workflow → .github/workflows/getff-go.yml (pinned golangci-lint bans gate)"
}

# _go_write_rules_lock — the go rules-lock variant (kickoff §1 W4 → J3). Writes
# .ai-factory/synthesizer-output/rules-lock.go.json — a REPRODUCIBILITY RECORD (emittedAt +
# sourceFingerprint = sha256 of the DELIVERED golangci config per _go_delivered_golangci_path:
# the getff-golangci.yml reference in the REFUSE cell, never the consumer's own file). A FUTURE
# rule-tests-surface reader / deps-hash suffix may consume it (spec §6, unshipped); no shipped
# consumer reads it today. Framework-owned, refresh-overwritten.
_go_write_rules_lock() {
  local lock_dir="$PROJECT_ROOT/.ai-factory/synthesizer-output"
  local lock="$lock_dir/rules-lock.go.json"
  local cfg
  cfg=$(_go_delivered_golangci_path)

  if [ "${DRY_RUN:-}" = "--dry-run" ]; then
    _go_log "[dry-run] would write the go rules-lock → .ai-factory/synthesizer-output/rules-lock.go.json"
    return 0
  fi

  mkdir -p "$lock_dir"
  # Fingerprint ladder (adapter-jig D2 — no-silent-fingerprint-degrade; mirrors 46-cargo.sh +
  # 45-python.sh): sha256 rungs first, md5 fallback rungs next (value carries its algorithm
  # prefix so a fallback digest is never mislabelled sha256), and BOTH degrade triggers — no
  # hash tool on PATH AND delivered-config-absent — warn LOUDLY to stderr
  # (attention-is-not-a-mechanism §1 / degrade-loudly): the "sha256:unknown" constant below is
  # a FAKE fingerprint, not an authoritative digest, and must never be silently trusted. Do NOT
  # hard-fail — the sourceFingerprint is an optional auditability field, not an install
  # precondition.
  local fp="sha256:unknown"
  if [ -e "$cfg" ]; then
    if command -v sha256sum >/dev/null 2>&1; then
      fp="sha256:$(sha256sum "$cfg" | awk '{print $1}')"
    elif command -v shasum >/dev/null 2>&1; then
      fp="sha256:$(shasum -a 256 "$cfg" | awk '{print $1}')"
    elif command -v md5 >/dev/null 2>&1; then          # BSD/macOS md5 fallback (lane parity: 46-cargo.sh ladder)
      fp="md5:$(md5 "$cfg" | awk '{print $NF}')"
    elif command -v md5sum >/dev/null 2>&1; then        # Linux md5sum fallback
      fp="md5:$(md5sum "$cfg" | awk '{print $1}')"
    else
      echo "  ⚠ getff: no hash tool (sha256sum/shasum/md5/md5sum); go rules-lock sourceFingerprint is non-authoritative" >&2
    fi
  else
    echo "  ⚠ getff: delivered golangci config missing ($cfg); go rules-lock sourceFingerprint is non-authoritative" >&2
  fi
  local now
  now=$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo unknown)
  # Schema (adapter-jig D3 — lock-schema-parity): the F11 CORE set {schemaVersion, framework,
  # version, ruleIds, emittedAt, sourceFingerprint} (packages/core/installer/types.ts RulesLock)
  # + per-lane extras (backend, note). ruleIds is [] by contract: go's ban surface is
  # golangci-lint TOML-style forbidigo config (pattern entries), not named ast-grep rule ids —
  # the core field is name-presence parity, its per-lane content may be empty. Gated cross-lane
  # by tests/install-sh/rules-lock-schema-parity.test.sh.
  cat > "$lock" <<EOF
{
  "schemaVersion": 1,
  "framework": "go",
  "version": null,
  "ruleIds": [],
  "backend": "go-golangci-lint",
  "emittedAt": "$now",
  "sourceFingerprint": "$fp",
  "note": "getff go lane reproducibility record (adapter-jig J3). sourceFingerprint hashes the DELIVERED golangci config (.golangci.yml when getff owns it; getff-golangci.yml in the REFUSE cell). A FUTURE rule-tests-surface reader / deps-hash suffix may consume emittedAt/sourceFingerprint (spec §6, unshipped)."
}
EOF
  _go_log "go rules-lock → .ai-factory/synthesizer-output/rules-lock.go.json (reproducibility record)"
}

# _go_firing_self_check — post-install firing PROOF (the «works» in the umbrella goal). Plants a
# violating .go file in an OS temp dir ONLY (mktemp -d — NEVER under the consumer's tracked tree,
# a binding STOP line), runs `golangci-lint run` with the DELIVERED config (per
# _go_delivered_golangci_path — getff-golangci.yml in the REFUSE cell, copied into the temp
# module as .golangci.yml so golangci-lint discovers it; the consumer's own config is never what
# we attest), and asserts the ban FIRES (the forbidigo diagnostic appears). Then removes the temp
# dir. Tool-gated: an absent go/golangci-lint → LOUD degrade printing the exact manual command
# (never silently green — attention-is-not-a-mechanism.md §1). rc=0 on every branch — a self-check
# must not abort the install.
#
# §1.3 LOAD-BEARING REPORTING LABEL (kickoff): when go/golangci-lint is absent on the host running
# `install.sh go`, the self-check prints "insufficient (tool absent)" — that is the honest label
# for a local run; it does NOT let the stage finish. The stage finishes when the runner arm
# (audit-self.yml go lane, F10 pin-parity mirror) is green and linked (T-EW-C posture).
# _go_dump_lint_output — print a captured golangci-lint run verbatim (indented) so a FAILED
# direction carries its own evidence into the log. Without it the self-check emitted a verdict
# («OVER-BROAD») with no trace of what actually fired, leaving «re-run the tool by hand» as the
# only diagnosis channel — a verdict nobody can act on from the log is not a mechanism
# (attention-is-not-a-mechanism.md §1). Incident 2026-08-06: CI run 31093381580 reported
# «1 ok · 0 SILENT · 1 OVER-BROAD» and the log carried zero golangci-lint output to root-cause it.
_go_dump_lint_output() {
  local _label="$1" _rc="$2" _text="$3"
  echo "    ↳ $_label: golangci-lint exit=$_rc, output verbatim:"
  if [ -n "$_text" ]; then
    printf '%s\n' "$_text" | sed 's/^/      | /'
  else
    echo "      | (no output)"
  fi
}

_go_firing_self_check() {
  echo ""
  local _pass=0 _silent=0 _degraded=0 _overbroad=0
  local _cfg
  _cfg=$(_go_delivered_golangci_path)
  echo "▶ getff firing self-check — proving the delivered golangci config ($(basename "$_cfg")) FIRES (planted violation in an OS temp dir)"

  # Both go AND golangci-lint must be on PATH. go alone is insufficient (golangci-lint is a
  # separate binary not bundled with the toolchain — divergence from the cargo lane where clippy
  # is a rustup component of the consumer's own rustc).
  if command -v golangci-lint >/dev/null 2>&1 && command -v go >/dev/null 2>&1 && [ -e "$_cfg" ]; then
    local _t; _t=$(mktemp -d)
    mkdir -p "$_t/selfcheck"
    # Copy the DELIVERED config into the temp module so golangci-lint auto-discovers it
    # (parity with cargo's clippy.toml copy into the temp crate).
    cp "$_cfg" "$_t/.golangci.yml"
    printf 'module getff-selfcheck\n\ngo 1.22\n' > "$_t/go.mod"
    # Planted violation: os.Getenv direct call — the exact pattern forbidigo bans.
    printf 'package selfcheck\n\nimport "os"\n\nfunc ConfigDirect() string {\n\treturn os.Getenv("HOME")\n}\n' > "$_t/selfcheck/violation.go"
    # Paired CLEAN CONTROL (adapter-jig E1): conforming code the delivered config must stay
    # quiet on. Without it an always-red config prints the same "enforcement is live" — the
    # RED direction alone cannot discriminate a working config from a broken one.
    printf 'package selfcheck\n\nimport "os"\n\nfunc Args() []string {\n\treturn os.Args\n}\n' > "$_t/selfcheck/clean.go"
    local _out _rc=0
    _out=$( cd "$_t" && golangci-lint run --enable forbidigo ./... 2>&1 ) || _rc=$?
    if [ "$_rc" -ne 0 ] && printf '%s' "$_out" | grep -qi 'forbidigo\|os\.Getenv'; then
      echo "  ✓ golangci-lint fired RED on the planted violation (forbidigo os.Getenv ban live)"
      _pass=$((_pass+1))
    else
      echo "  ✗ golangci-lint did NOT fire on the planted violation — the delivered config is SILENT (delivery bug)"
      _go_dump_lint_output "planted-violation run" "$_rc" "$_out"
      _silent=$((_silent+1))
    fi
    # Clean control: the delivered config must NOT flag os.Args (only os.Getenv is banned).
    local _out_clean _rc_clean=0
    _out_clean=$( cd "$_t" && rm -f "$_t/selfcheck/violation.go" && golangci-lint run --enable forbidigo ./... 2>&1 ) || _rc_clean=$?
    if [ "$_rc_clean" -eq 0 ]; then
      echo "  ✓ golangci-lint clean control GREEN — no diagnostic on conforming code (config discriminates)"
      _pass=$((_pass+1))
    else
      echo "  ✗ golangci-lint FIRED on the clean control — the delivered config is OVER-BROAD (an always-red config is not enforcement)"
      _go_dump_lint_output "clean-control run" "$_rc_clean" "$_out_clean"
      # The .go files golangci-lint actually saw on this run. Discriminates the two failure
      # classes the exit code alone cannot: a genuinely over-broad pattern (fires on clean.go)
      # vs. a stale/leftover violation.go still in the module (the rm did not take effect).
      echo "    ↳ .go files present in the temp module at clean-control time:"
      ( cd "$_t" && find . -name '*.go' -print ) 2>&1 | sed 's/^/      | /'
      _overbroad=$((_overbroad+1))
    fi
    rm -rf "$_t"
  else
    echo "  ⚠ go or golangci-lint not on PATH (or the delivered config missing) — firing NOT proven (degrade, NOT green)."
    echo "    Per kickoff §1.3, the local label is «insufficient (tool absent)» — the stage is NOT done."
    echo "    Verify manually from your module root:"
    echo "      go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2"
    echo "      golangci-lint run --enable forbidigo --config .golangci.yml ./...    # must exit non-zero on os.Getenv"
    _degraded=$((_degraded+1))
  fi

  echo ""
  if [ "$_silent" -gt 0 ] || [ "$_overbroad" -gt 0 ]; then
    echo "⚠  getff self-check: $_pass ok · $_silent SILENT · $_overbroad OVER-BROAD — the delivered golangci config failed a direction (SILENT = no fire on bad input; OVER-BROAD = fired on clean input); review above before relying on it."
  elif [ "$_degraded" -gt 0 ]; then
    echo "⚠  getff self-check: $_pass proven-firing · $_degraded NOT proven (tool absent) — a skipped check is NOT green; run the manual command(s) above to prove it."
  else
    echo "✓ getff self-check: the delivered golangci config fired RED on a planted violation and stayed GREEN on the clean control — enforcement is live."
  fi
  return 0
}

# deliver_go_toolchain — the go-lane entrypoint (called under the activation guard below).
deliver_go_toolchain() {
  local tpl="${GO_TEMPLATE_DIR:-$PKG_ROOT/packages/core/templates/go}"
  _GO_LOG_FILE="$PROJECT_ROOT/.getff-go-install.log"

  if [ ! -d "$tpl" ]; then
    echo "  ⚠ go templates not found at $tpl — skipping go delivery" >&2
    return 0
  fi

  echo "▶ Go toolchain (getff) — augment-first delivery"
  if [ "${DRY_RUN:-}" != "--dry-run" ]; then
    { printf '# getff go delivery — run at %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo unknown)"; } >> "$_GO_LOG_FILE"
  fi

  _go_deliver_golangci "$tpl"
  _go_deliver_ci "$tpl"
  _go_write_rules_lock

  # adapter-jig C4 (no-orphan-residue): on a refresh pass, loudly report getff-header-marked
  # top-level files the CURRENT template set no longer delivers (lib.sh report_getff_orphans).
  # Report-only — J2 decisions log #8; parity with the cargo lane.
  if [ "${GETFF_TOOLCHAIN_REFRESH:-}" = "1" ]; then
    report_getff_orphans go \
      .golangci.yml getff-golangci.yml \
      .github/workflows/getff-go.yml
  fi

  echo "  ✓ Go toolchain delivery complete (see .getff-go-install.log for the audit trail)."
}

# ── Test seam: define the functions above but skip the auto-delivery (tests drive per-fixture) ──
if [ "${GO_LAYER_LIB_ONLY:-}" = "1" ]; then
  return 0 2>/dev/null || true
fi

# ── Activation guard: INERT unless the go lane is explicitly selected (do_go_lane sets it) ──
if [ "${GETFF_TOOLCHAIN:-}" = "go" ]; then
  deliver_go_toolchain
fi
